/**
 * @file esolver_nep.cpp
 * @brief Implementation of ESolver_NEP class for neuroevolution potential (NEP).
 *
 * This file contains the implementation of the ESolver_NEP class, which is used for solving the energy and forces in a
 * NEP simulation.
 * NEP is a method for training deep neural networks to accurately predict the potential energy surface of a
 * molecular system.
 *
 * For more information about NEP, see the following reference:
 * 1. https://gpumd.org/potentials/nep.html
 * 2. https://doi.org/10.1002/mgea.70028
 *
 * @author MoseyQAQ
 * @date 2025-10-10
 */
#include "esolver_nep.h"
#include "esolver_nep_postprocess.h"
#include "source_io/module_parameter/parameter.h"

#ifdef __CUDA
// Forward-declare the CUDA kernel entry point (defined in nep_cuda_compute.cu).
// Avoid including ".cuh" here — it has __device__ syntax that g++ cannot parse.
extern void nep_cuda_compute(
    int N,
    const int *type,
    const int *NN_radial, const int *NL_radial,
    const int *NN_angular, const int *NL_angular,
    const double *x12_radial, const double *y12_radial, const double *z12_radial,
    const double *x12_angular, const double *y12_angular, const double *z12_angular,
    int n_max_radial, int n_max_angular,
    int basis_size_radial, int basis_size_angular,
    int L_max, int num_L, int num_types, int num_types_sq, int num_c_radial,
    int dim, int num_neurons1, int version,
    const double *rc_radial, const double *rc_angular,
    const double *ann_c, int num_para,
    const double *w0, const double *b0, const double *w1, const double *b1,
    const double *q_scaler,
    double *potential, double *force, double *virial);
#endif

#include "source_base/parallel_common.h"
#include "source_base/timer.h"
#include "source_io/module_output/output_log.h"
#include "source_io/module_output/cif_io.h"

#include <unordered_map>

using namespace ModuleESolver;

void ESolver_NEP::before_all_runners(UnitCell& ucell, const Input_para& inp)
{
    nep_potential = 0.0;
    nep_force.create(ucell.nat, 3);
    nep_virial.create(3, 3);
    atype.resize(ucell.nat);
    _e.resize(ucell.nat);
    _f.resize(3 * ucell.nat);
    _v.resize(9 * ucell.nat);
    cell.resize(9);
    coord.resize(3 * ucell.nat);

#ifdef __CUDA
    if (inp.device == "gpu")
    {
        init_nep_cuda_postprocess_workspace(cuda_postprocess_workspace, ucell.nat);

        // Allocate neighbor list buffers for GPU compute path
        const int N = ucell.nat;
        const int MN = NEP_GPU_MN;
        g_NN_radial.resize(N);
        g_NL_radial.resize(N * MN);
        g_NN_angular.resize(N);
        g_NL_angular.resize(N * MN);
        r12.resize(N * MN * 6); // 3 radial + 3 angular components
    }
#endif

    ModuleIO::CifParser::write(PARAM.globalv.global_out_dir + "STRU.cif",
                               ucell,
                               "# Generated by ABACUS ModuleIO::CifParser",
                               "data_?");

#ifdef __NEP
    /// determine the type map from STRU to NEP model
    type_map(ucell);
#endif
}

void ESolver_NEP::runner(UnitCell& ucell, const int istep)
{
    ModuleBase::TITLE("ESolver_NEP", "runner");
    ModuleBase::timer::start("ESolver_NEP", "runner");

    prepare_input_buffers(ucell);

#ifdef __NEP
    nep_potential = 0.0;
    nep_force.zero_out();
    nep_virial.zero_out();

#ifdef __CUDA
    if (PARAM.inp.device == "gpu")
    {
        // === GPU compute path ===
        const int N = ucell.nat;
        const int MN = NEP_GPU_MN;
        const int size_x12 = N * MN;

        // Step 1: CPU computes neighbor list
        find_neighbor_list_small_box(
            nep.paramb.rc_radial_max,
            nep.paramb.rc_angular_max,
            N, MN,
            cell, coord,
            num_cells, ebox,
            g_NN_radial, g_NL_radial,
            g_NN_angular, g_NL_angular,
            r12);

        // Step 2: GPU neural network forward pass
        // r12 layout: [radial xyz][angular xyz], each block size_x12 doubles
        double* x12_radial    = r12.data();
        double* y12_radial    = r12.data() + size_x12;
        double* z12_radial    = r12.data() + 2 * size_x12;
        double* x12_angular   = r12.data() + 3 * size_x12;
        double* y12_angular   = r12.data() + 4 * size_x12;
        double* z12_angular   = r12.data() + 5 * size_x12;

        // NEP model parameters (all public members of NEP class)
        const auto& p = nep.paramb;
        const auto& a = nep.annmb;

        nep_cuda_compute(
            N,
            atype.data(),
            g_NN_radial.data(), g_NL_radial.data(),
            g_NN_angular.data(), g_NL_angular.data(),
            x12_radial, y12_radial, z12_radial,
            x12_angular, y12_angular, z12_angular,
            // NEP model hyperparameters
            p.n_max_radial, p.n_max_angular,
            p.basis_size_radial, p.basis_size_angular,
            p.L_max, p.num_L,
            static_cast<int>(p.num_types),
            static_cast<int>(p.num_types_sq),
            static_cast<int>(p.num_c_radial),
            a.dim, a.num_neurons1, p.version,
            p.rc_radial, p.rc_angular,
            a.c, a.num_para,
            // w0/b0/w1 are const double* [94] arrays (per atom type),
            // w0[0] passes the first type's weight pointer (flat contiguous in NEP_CPU).
            a.w0[0], a.b0[0], a.w1[0], a.b1,
            p.q_scaler,
            // Output buffers
            _e.data(), _f.data(), _v.data());
    }
    else
#endif
    {
        // === CPU compute path (original) ===
        nep.compute(atype, cell, coord, _e, _f, _v);
    }

    postprocess_outputs(ucell);
#else
    ModuleBase::WARNING_QUIT("ESolver_NEP", "Please recompile with -D__NEP");
#endif
    ModuleBase::timer::end("ESolver_NEP", "runner");
}

void ESolver_NEP::prepare_input_buffers(const UnitCell& ucell)
{
    ModuleBase::timer::start("ESolver_NEP", "prepare_input");

    // NEP uses column-major cell and structure-of-arrays coordinates.
    cell[0] = ucell.latvec.e11 * ucell.lat0_angstrom;
    cell[1] = ucell.latvec.e21 * ucell.lat0_angstrom;
    cell[2] = ucell.latvec.e31 * ucell.lat0_angstrom;
    cell[3] = ucell.latvec.e12 * ucell.lat0_angstrom;
    cell[4] = ucell.latvec.e22 * ucell.lat0_angstrom;
    cell[5] = ucell.latvec.e32 * ucell.lat0_angstrom;
    cell[6] = ucell.latvec.e13 * ucell.lat0_angstrom;
    cell[7] = ucell.latvec.e23 * ucell.lat0_angstrom;
    cell[8] = ucell.latvec.e33 * ucell.lat0_angstrom;

    int iat = 0;
    const int nat = ucell.nat;
    for (int it = 0; it < ucell.ntype; ++it)
    {
        for (int ia = 0; ia < ucell.atoms[it].na; ++ia)
        {
            coord[iat] = ucell.atoms[it].tau[ia].x * ucell.lat0_angstrom;
            coord[iat + nat] = ucell.atoms[it].tau[ia].y * ucell.lat0_angstrom;
            coord[iat + 2 * nat] = ucell.atoms[it].tau[ia].z * ucell.lat0_angstrom;
            iat++;
        }
    }
    assert(ucell.nat == iat);

    ModuleBase::timer::end("ESolver_NEP", "prepare_input");
}

void ESolver_NEP::postprocess_outputs(const UnitCell& ucell)
{
    ModuleBase::timer::start("ESolver_NEP", "postprocess");

    // unit conversion
    const double fact_e = 1.0 / ModuleBase::Ry_to_eV;
    const double fact_f = 1.0 / (ModuleBase::Ry_to_eV * ModuleBase::ANGSTROM_AU);
    const double fact_v = 1.0 / (ucell.omega * ModuleBase::Ry_to_eV);

#ifdef __CUDA
    if (PARAM.inp.device == "gpu")
    {
        postprocess_nep_cuda(ucell.nat,
                             _e.data(),
                             _f.data(),
                             _v.data(),
                             fact_e,
                             fact_f,
                             fact_v,
                             nep_potential,
                             nep_force,
                             nep_virial,
                             cuda_postprocess_workspace);
    }
    else
#endif
    {
        postprocess_nep_cpu(ucell.nat,
                            _e.data(),
                            _f.data(),
                            _v.data(),
                            fact_e,
                            fact_f,
                            fact_v,
                            nep_potential,
                            nep_force,
                            nep_virial);
    }

    GlobalV::ofs_running << " #TOTAL ENERGY# " << std::setprecision(11) << nep_potential * ModuleBase::Ry_to_eV << " eV"
                         << std::endl;

    ModuleBase::timer::end("ESolver_NEP", "postprocess");
}

double ESolver_NEP::cal_energy()
{
    return nep_potential;
}

void ESolver_NEP::cal_force(UnitCell& ucell, ModuleBase::matrix& force)
{
    force = nep_force;
    ModuleIO::print_force(GlobalV::ofs_running, ucell, "TOTAL-FORCE (eV/Angstrom)", force, false);
}

void ESolver_NEP::cal_stress(UnitCell& ucell, ModuleBase::matrix& stress)
{
    stress = nep_virial;
    ModuleIO::print_stress("TOTAL-STRESS", stress, true, false, GlobalV::ofs_running);

    // external stress
    double unit_transform = ModuleBase::RYDBERG_SI / pow(ModuleBase::BOHR_RADIUS_SI, 3) * 1.0e-8;
    double external_stress[3] = {PARAM.inp.press1, PARAM.inp.press2, PARAM.inp.press3};
    for (int i = 0; i < 3; i++)
    {
        stress(i, i) -= external_stress[i] / unit_transform;
    }
}

void ESolver_NEP::after_all_runners(UnitCell& ucell)
{
#ifdef __CUDA
    release_nep_cuda_postprocess_workspace(cuda_postprocess_workspace);
#endif

    GlobalV::ofs_running << "\n --------------------------------------------" << std::endl;
    GlobalV::ofs_running << std::setprecision(16);
    GlobalV::ofs_running << " !FINAL_ETOT_IS " << nep_potential * ModuleBase::Ry_to_eV << " eV" << std::endl;
    GlobalV::ofs_running << " --------------------------------------------\n\n" << std::endl;
}

#ifdef __NEP
void ESolver_NEP::type_map(const UnitCell& ucell)
{
    // parse the element list from NEP model file
    std::unordered_map<std::string, int> label;
    std::string temp;
    for (int i = 0; i < nep.element_list.size(); ++i)
    {
        label[nep.element_list[i]] = i; //> label: map from element string to index int.
    }

    std::cout << "\n Element list of model file " << nep_file << " " << std::endl;
    std::cout << " ----------------------------------------------------------------";
    int count = 0;
    for (auto it = label.begin(); it != label.end(); ++it)
    {
        if (count % 5 == 0)
        {
            std::cout << std::endl;
            std::cout << "  ";
        }
        count++;
        temp = it->first + ": " + std::to_string(it->second);
        std::cout << std::left << std::setw(10) << temp;
    }
    std::cout << "\n -----------------------------------------------------------------" << std::endl;

    // parse the atype based on the element list
    int iat = 0;
    for (int it = 0; it < ucell.ntype; ++it)
    {
        for (int ia = 0; ia < ucell.atoms[it].na; ++ia)
        {
            if (label.find(ucell.atoms[it].label) == label.end())
            {
                ModuleBase::WARNING_QUIT("ESolver_NEP",
                                         "The label " + ucell.atoms[it].label + " is not found in the type map.");
            }
            atype[iat] = label[ucell.atoms[it].label];
            iat++;
        }
    }
    assert(ucell.nat == iat);
}
#endif
