add_library(
    surchem
    OBJECT
    surchem.cpp
    h_corr_pw.cpp
    sccs/h_corr_sccs.cpp
    pcc/h_corr_pcc.cpp
    cal_epsilon.cpp
    cal_pseudo.cpp
    cal_totn.cpp
    cal_vcav.cpp
    cal_vel.cpp
    minimize_cg.cpp
    sol_force.cpp
    sccs/sccs_cavity.cpp
    sccs/sccs_charge.cpp
    sccs/sccs_driver.cpp
    sccs/sccs_functional.cpp
    sccs/sccs_nonel.cpp
    sccs/sccs_parameters.cpp
    pcc/sccs_pcc.cpp
    pcc/sccs_pcc_2d.cpp
    pcc/sccs_pcc_2d_coulomb.cpp
    pcc/sccs_pcc_coulomb.cpp
    sccs/sccs_poisson.cpp
    sccs/sccs_pw_coulomb.cpp
    sccs/sccs_pw_charge.cpp
    sccs/sccs_pw_force.cpp
    sccs/sccs_pw_nonel.cpp
    sccs/sccs_pw_reduction.cpp
    sccs/sccs_periodic.cpp
)

if(ENABLE_COVERAGE)
  add_coverage(surchem)
endif()

IF (BUILD_TESTING)
  if(ENABLE_MPI)
    add_subdirectory(test)
  endif()
endif()
