calculation:
  type: relax
  init_structure: inputs/init.extxyz
  fmax: 0.10
  max_steps: 1
  optimizer: BFGS
  trajectory: helper_relax.traj
  logfile: helper_relax.log

calculator:
  name: abacus
  abacus:
    command: abacus
    mpi: 1
    omp: 1
    directory: helper_abacus_run
    kpts: [1, 1, 1]
    parameters:
      calculation: scf
      basis_type: lcao
      ks_solver: genelpa
      ecutwfc: 100
      dft_functional: pbe
      symmetry: 0
      scf_thr: 1e-6
      scf_nmax: 100
      cal_force: 1
      cal_stress: 0
      pseudo_dir: ../../../../../tests/PP_ORB
      orbital_dir: ../../../../../tests/PP_ORB
      pseudopotentials:
        Si: Si_ONCV_PBE-1.0.upf
      basissets:
        Si: Si_gga_8au_100Ry_2s2p1d.orb
