name: Feature Request
description: For users or developers who want to propose new features to be added or suggest improvements or enhancements to existing features.
labels: [Feature Request]
assignees: mohanchen

body:
- type: textarea
  attributes:
    label: Background
    description: |
      A clear and concise description of why this new feature is important.
    placeholder: |
      Example: A new feature is requested based on emerging research in density functional theory ...    
      Implementing this feature will significantly enhance ABACUS's capabilities and improve user experience by enabling them to ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen.
    placeholder: |
      Example: It is suggested to implement a novel functionality with the LCAO basis, enabling users to efficiently ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or references about the feature request here.
    placeholder: |
      Example: Here is a mockup of the proposed feature (insert screenshot or link to design), along with relevant research articles and resources that support the implementation of this feature...

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
