name: Performance
description: For users or developers to report software performance issues from a user perspective, such as slow response times, high resource usage, or scalability issues.
labels: [Performance]
assignees: dyzheng

body:
- type: textarea
  attributes:
    label: Details
    description: |
      Please provide details about the performance issue you are experiencing. Include any relevant information such as the system you are using ABACUS with, the specific task you were performing, and any error messages you received.
    placeholder: |
      Example: I am calculate a system with 200 atoms, and the SCF calculation is very slow. I am performing the calculation on a cluster with 4 nodes, each with 32 cores and 128 GB memory. I have tried to increase the number of MPI processes, but the calculation is still slow ...
  validations:
      required: true
- type: markdown
  attributes:
    value: >
      Thank you for reporting this performance issue. We will investigate and do our best to resolve it. 🚀