#include "fssh_driver.h"

#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <sstream>
#include <tuple>
#include <utility>

#include <mpi.h>
#include "source_cell/unitcell.h"

// LAPACK 外部声明: SVD (Procrustes 对齐) + LU 分解/求逆 (Löwdin 方法)
extern "C" {
void dgesvd_(const char* jobu, const char* jobvt, const int* m, const int* n,
             double* a, const int* lda, double* s, double* u, const int* ldu,
             double* vt, const int* ldvt, double* work, const int* lwork, int* info);
void dgetrf_(const int* m, const int* n, double* a, const int* lda,
             int* ipiv, int* info);
void dgetri_(const int* n, double* a, const int* lda,
             const int* ipiv, double* work, const int* lwork, int* info);
}

FsshDriver::FsshDriver() : nstates_(0), nbasis_(0), dt_(0.0), current_state_(0),
                           nocc_(0), nks_total_(0) {
    std::random_device rd;
    gen_.seed(rd());
    rand_dist_ = std::uniform_real_distribution<double>(0.0, 1.0);
}

FsshDriver::~FsshDriver() {}

// [FSSH修改说明] init 函数增加 nocc 和 nks_total 参数
// 原代码: void FsshDriver::init(int nbasis_in, int nstates_in, double dt_in, int start_state) {
//     nbasis_ = nbasis_in; nstates_ = nstates_in; dt_ = dt_in; current_state_ = start_state;
//     electronic_coeffs_.assign(nstates_, ...);
// }
// 修改原因: TDA NAC 需要知道 nocc (占据轨道数) 来正确索引 X^I_{ia} 系数中的
//   占据轨道 i ∈ [0, nocc) 和虚轨道 a ∈ [0, nvirt)，
//   以及 nks_total (总KS轨道数) 来计算全 MO 重叠矩阵 S^{MO}_{pq}
void FsshDriver::init(int nbasis_in, int nstates_in, double dt_in, int start_state,
                       int nocc, int nks_total) {
    nbasis_ = nbasis_in;
    nstates_ = nstates_in;
    dt_ = dt_in;
    current_state_ = start_state;
    nocc_ = nocc;
    nks_total_ = nks_total;

    // Reset electronic coefficients safely
    electronic_coeffs_.assign(nstates_, std::complex<double>(0.0, 0.0));
    electronic_coeffs_[start_state] = std::complex<double>(1.0, 0.0);

    // Clear Casida cache
    casida_wfcs_old_.clear();
}

void FsshDriver::set_casida_cache(const std::vector<CasidaWavefunction>& wfcs) {
    casida_wfcs_old_ = wfcs;
}

/// @brief Parses the asynchronous overlap matrix from a CSR format file.
/// @details Scans the output file for the latest "IONIC_STEP" and parses the sparse matrix 
/// (values, column indices, and row pointers) into a dense complex matrix.
/// @param filename The path to the syns_nao.csr file generated by ABACUS.
/// @return A dense complex matrix representing the atomic orbital overlap.
ModuleBase::ComplexMatrix FsshDriver::parse_latest_csr(const std::string& filename) {
    ModuleBase::ComplexMatrix s_ao(nbasis_, nbasis_); // Initialize to zeros
    
    std::ifstream ifs(filename);
    if (!ifs.is_open()) {
        std::cerr << "[FSSH WARNING] Cannot open " << filename 
                  << " yet (likely at step 0). Skipping." << std::endl;
        return s_ao;
    }

    std::vector<std::string> lines;
    std::string line;
    while (std::getline(ifs, line)) {
        lines.push_back(line);
    }
    ifs.close();

    // Find the last occurrence of "IONIC_STEP" in reverse order
    int last_idx = -1;
    for (int i = static_cast<int>(lines.size()) - 1; i >= 0; --i) {
        if (lines[i].find("IONIC_STEP") != std::string::npos) {
            last_idx = i;
            break;
        }
    }

    if (last_idx == -1) {
        return s_ao; // File has not started writing ionic steps yet
    }

    try {
        int current_idx = last_idx + 1;
        int nnz = 0;
        
        // 1. Identify the line containing the number of non-zero elements (nnz)
        while (current_idx < static_cast<int>(lines.size())) {
            std::string cur_line = lines[current_idx];
            size_t start = cur_line.find_first_not_of(" \t\r\n");
            
            // Skip empty lines, comments ('#'), or metadata containing "Matrix"
            if (start == std::string::npos || cur_line[start] == '#' || 
                cur_line.find("Matrix") != std::string::npos) {
                current_idx++;
                continue;
            }
            
            // First valid data line found. Extract the 4th integer as nnz.
            std::stringstream ss(cur_line);
            int rx, ry, rz;
            ss >> rx >> ry >> rz >> nnz;
            current_idx++;
            break;
        }

        if (nnz <= 0) {
            throw std::runtime_error("Failed to extract nnz, or nnz <= 0");
        }

        // Helper lambda to safely extract multi-line data blocks
        auto read_data_block = [&](int expected_count, const std::string& marker) {
            std::vector<double> temp_vec; 
            
            // Fast-forward to the target marker
            while (current_idx < static_cast<int>(lines.size()) && 
                   lines[current_idx].find(marker) == std::string::npos) {
                current_idx++;
            }
            current_idx++; // Skip the marker line itself

            // Accumulate numerical values until expected_count is met
            while (temp_vec.size() < static_cast<size_t>(expected_count) && 
                   current_idx < static_cast<int>(lines.size())) {
                std::stringstream ss(lines[current_idx]);
                double val;
                while (ss >> val) {
                    temp_vec.push_back(val);
                    if (temp_vec.size() == static_cast<size_t>(expected_count)) {
                        break;
                    }
                }
                current_idx++;
            }
            return temp_vec;
        };

        // 2. Read the three main CSR blocks in order
        std::vector<double> values = read_data_block(nnz, "# CSR values");
        
        std::vector<double> raw_col = read_data_block(nnz, "# CSR column indices");
        std::vector<int> col_ind;
        col_ind.reserve(raw_col.size());
        for (double v : raw_col) {
            col_ind.push_back(static_cast<int>(v));
        }

        std::vector<double> raw_row = read_data_block(nbasis_ + 1, "# CSR row pointers");
        std::vector<int> row_ptr;
        row_ptr.reserve(raw_row.size());
        for (double v : raw_row) {
            row_ptr.push_back(static_cast<int>(v));
        }

        // 3. Map sparse CSR format into the dense ComplexMatrix
        for (int mu = 0; mu < nbasis_; ++mu) {
            for (int idx = row_ptr[mu]; idx < row_ptr[mu + 1]; ++idx) {
                int nu = col_ind[idx];
                double val = values[idx];
                
                // Out-of-bounds safety check
                if (mu >= nbasis_ || nu >= nbasis_ || mu < 0 || nu < 0) {
                    continue;
                }
                
                s_ao(mu, nu) = std::complex<double>(val, 0.0);
            }
        }

    } catch (const std::exception& e) {
        std::cerr << "[FSSH ERROR] Failed to parse CSR matrix: " << e.what() << std::endl;
    }

    return s_ao;
}

// ====================================================================
// Löwdin 精确 CIS/TDA 多体态重叠
// ====================================================================
//
// 精确公式 (Malmqvist 1986, Plasser et al. 2016):
//   基态-基态:   Σ_{00} = det(S^{oo})
//   基态-激发态: Σ_{0J} = det(S^{oo}) × Σ_{jb} [(S^{oo})^{-1} S^{ov}]_{jb} × X^J_{jb}
//   激发态-基态: Σ_{I0} = det(S^{oo}) × Σ_{ia} X^I_{ia} × [S^{vo} (S^{oo})^{-1}]_{ai}
//   激发态-激发态:
//     Σ_{IJ} = det(S^{oo}) × Σ_{ij} [(S^{oo})^{-1}]_{ji} × Σ_{ab} X^I_{ia} S̃_{ab} X^J_{jb}
//     其中 S̃_{ab} = S^{vv}_{ab} - Σ_{mn} S^{vo}_{am} [(S^{oo})^{-1}]_{mn} S^{ov}_{nb}
//
// 参数说明:
//   occ_phase[i_lr]: 占据轨道相位修正 (±1)，与方向 B 使用相同的规范
//   det_Soo_out: 可选输出 det(S^{oo})，用于诊断
// ====================================================================
void FsshDriver::compute_lowdin_sigma(const ModuleBase::ComplexMatrix& coef_old,
                                       const ModuleBase::ComplexMatrix& coef_new,
                                       const ModuleBase::ComplexMatrix& s_ao_dense,
                                       const std::vector<CasidaWavefunction>& casida_old,
                                       const std::vector<CasidaWavefunction>& casida_new,
                                       int nocc_lr, int nvirt_lr, int occ_offset,
                                       const std::vector<double>& occ_phase,
                                       ModuleBase::ComplexMatrix& Sigma_lowdin,
                                       double* det_Soo_out) {

    const int n_lr = nocc_lr + nvirt_lr;

    // ---- 辅助函数: LR 局部索引 → KS 全局索引 ----
    // 占据: loc ∈ [0, nocc_lr) → KS: occ_offset + loc
    // 虚:   loc ∈ [nocc_lr, n_lr) → KS: nocc_ + (loc - nocc_lr)
    auto local_to_ks = [&](int loc) -> int {
        if (loc < nocc_lr) return occ_offset + loc;
        else return nocc_ + (loc - nocc_lr);
    };

    // ================================================================
    // Step 1: 构建完整 MO 重叠矩阵 S^{MO}_{pq}
    //   p,q 遍历 LR 子空间: [0, nocc_lr) = 占据, [nocc_lr, n_lr) = 虚
    //   S^{MO}_{pq} = Σ_{μν} C*_{p_ks,μ}(t) S^{AO}_{μν} C_{q_ks,ν}(t')
    //   并应用占据轨道相位修正 (与方向 B 保持相同规范)
    // ================================================================
    std::vector<double> s_mo(n_lr * n_lr, 0.0);
    for (int p = 0; p < n_lr; ++p) {
        int p_ks = local_to_ks(p);
        if (p_ks >= coef_old.nr) continue;
        for (int q = 0; q < n_lr; ++q) {
            int q_ks = local_to_ks(q);
            if (q_ks >= coef_new.nr) continue;
            double val = 0.0;
            for (int mu = 0; mu < nbasis_; ++mu) {
                for (int nu = 0; nu < nbasis_; ++nu) {
                    val += (std::conj(coef_old(p_ks, mu)) * s_ao_dense(mu, nu)
                            * coef_new(q_ks, nu)).real();
                }
            }
            s_mo[p * n_lr + q] = val;
        }
    }

    // 对新步占据轨道列应用相位修正 (与方向 B 一致)
    for (int q = 0; q < nocc_lr; ++q) {
        if (occ_phase[q] < 0.0) {
            for (int p = 0; p < n_lr; ++p) {
                s_mo[p * n_lr + q] *= -1.0;
            }
        }
    }

    // ---- 辅助宏: 从 s_mo 提取子块 ----
    // S^{oo}_{ij} = s_mo[i * n_lr + j]                  i,j ∈ [0, nocc_lr)
    // S^{ov}_{ib} = s_mo[i * n_lr + nocc_lr + b]        i ∈ [0, nocc_lr), b ∈ [0, nvirt_lr)
    // S^{vo}_{aj} = s_mo[(nocc_lr + a) * n_lr + j]      a ∈ [0, nvirt_lr), j ∈ [0, nocc_lr)
    // S^{vv}_{ab} = s_mo[(nocc_lr + a) * n_lr + nocc_lr + b]
    auto Soo = [&](int i, int j) -> double { return s_mo[i * n_lr + j]; };
    auto Sov = [&](int i, int b) -> double { return s_mo[i * n_lr + nocc_lr + b]; };
    auto Svo = [&](int a, int j) -> double { return s_mo[(nocc_lr + a) * n_lr + j]; };
    auto Svv = [&](int a, int b) -> double { return s_mo[(nocc_lr + a) * n_lr + nocc_lr + b]; };

    // ================================================================
    // Step 2: LU 分解 S^{oo}，计算 det(S^{oo}) 和 (S^{oo})^{-1}
    // ================================================================
    std::vector<double> Soo_cm(nocc_lr * nocc_lr);  // 列主序 (LAPACK)
    for (int i = 0; i < nocc_lr; ++i)
        for (int j = 0; j < nocc_lr; ++j)
            Soo_cm[i + j * nocc_lr] = Soo(i, j);  // col-major: [row + col * lda]

    std::vector<int> ipiv(nocc_lr);
    int info = 0;
    int nn = nocc_lr;

    // LU 分解: S^{oo} = P L U
    dgetrf_(&nn, &nn, Soo_cm.data(), &nn, ipiv.data(), &info);

    if (info != 0) {
        // LU 失败，回退: Sigma_lowdin 置为单位阵
        for (int I = 0; I < nstates_; ++I)
            Sigma_lowdin(I, I) = std::complex<double>(1.0, 0.0);
        if (det_Soo_out) *det_Soo_out = 1.0;
        return;
    }

    // 从 LU 对角线提取行列式
    double det_Soo = 1.0;
    int sign_perm = 0;
    for (int i = 0; i < nocc_lr; ++i) {
        det_Soo *= Soo_cm[i + i * nocc_lr];        // U 的对角元
        if (ipiv[i] != i + 1) sign_perm++;           // LAPACK ipiv 是 1-based
    }
    if (sign_perm % 2 == 1) det_Soo = -det_Soo;
    if (det_Soo_out) *det_Soo_out = det_Soo;

    // 求逆: (S^{oo})^{-1}，就地覆盖 Soo_cm
    int lwork = -1;
    double wquery;
    dgetri_(&nn, Soo_cm.data(), &nn, ipiv.data(), &wquery, &lwork, &info);
    lwork = static_cast<int>(wquery) + 1;
    std::vector<double> work(lwork);
    dgetri_(&nn, Soo_cm.data(), &nn, ipiv.data(), work.data(), &lwork, &info);
    // 现在 Soo_cm = (S^{oo})^{-1}，列主序: Soo_inv(i,j) = Soo_cm[i + j * nocc_lr]

    if (info != 0) {
        for (int I = 0; I < nstates_; ++I)
            Sigma_lowdin(I, I) = std::complex<double>(1.0, 0.0);
        return;
    }

    auto Soo_inv = [&](int i, int j) -> double { return Soo_cm[i + j * nocc_lr]; };

    // ================================================================
    // Step 3: 计算辅助矩阵
    //   Q_{jb} = [(S^{oo})^{-1} S^{ov}]_{jb} = Σ_k Soo_inv(j,k) * S^{ov}(k,b)
    //   R_{ia} = [S^{vo} (S^{oo})^{-1}]_{ai} → 转置存为 R[i * nvirt + a]
    //          = Σ_j S^{vo}(a,j) * Soo_inv(j,i)
    // ================================================================
    std::vector<double> Q(nocc_lr * nvirt_lr, 0.0);  // Q[j * nvirt_lr + b]
    for (int j = 0; j < nocc_lr; ++j)
        for (int b = 0; b < nvirt_lr; ++b)
            for (int k = 0; k < nocc_lr; ++k)
                Q[j * nvirt_lr + b] += Soo_inv(j, k) * Sov(k, b);

    std::vector<double> R(nocc_lr * nvirt_lr, 0.0);  // R[i * nvirt_lr + a]
    for (int i = 0; i < nocc_lr; ++i)
        for (int a = 0; a < nvirt_lr; ++a)
            for (int j = 0; j < nocc_lr; ++j)
                R[i * nvirt_lr + a] += Svo(a, j) * Soo_inv(j, i);

    // ================================================================
    // Step 4: 计算 Schur 补 S̃^{vv}_{ab} = S^{vv}_{ab} - Σ_i S^{vo}_{ai} Q_{ib}
    //   = S^{vv}_{ab} - [S^{vo} (S^{oo})^{-1} S^{ov}]_{ab}
    // ================================================================
    std::vector<double> Stilde(nvirt_lr * nvirt_lr, 0.0);  // 行主序
    for (int a = 0; a < nvirt_lr; ++a)
        for (int b = 0; b < nvirt_lr; ++b) {
            double correction = 0.0;
            for (int i = 0; i < nocc_lr; ++i)
                correction += Svo(a, i) * Q[i * nvirt_lr + b];
            Stilde[a * nvirt_lr + b] = Svv(a, b) - correction;
        }

    // ================================================================
    // Step 5: 构建 Sigma_lowdin 矩阵
    // ================================================================

    // 基态-基态: Σ_{00} = det(S^{oo})
    Sigma_lowdin(0, 0) = std::complex<double>(det_Soo, 0.0);

    // 基态→激发态: Σ_{0J} = det(S^{oo}) × Σ_{jb} Q_{jb} × X^J_{jb}
    for (int J = 1; J < nstates_; ++J) {
        if (J >= static_cast<int>(casida_new.size())) continue;
        const auto& X_J = casida_new[J].X_coeffs;
        double val = 0.0;
        for (int j = 0; j < nocc_lr; ++j)
            for (int b = 0; b < nvirt_lr; ++b) {
                int idx = j * nvirt_lr + b;
                if (idx < static_cast<int>(X_J.size()))
                    val += Q[j * nvirt_lr + b] * X_J[idx];
            }
        Sigma_lowdin(0, J) = std::complex<double>(det_Soo * val, 0.0);
    }

    // 激发态→基态: Σ_{I0} = det(S^{oo}) × Σ_{ia} X^I_{ia} × R_{ia}
    for (int I = 1; I < nstates_; ++I) {
        if (I >= static_cast<int>(casida_old.size())) continue;
        const auto& X_I = casida_old[I].X_coeffs;
        double val = 0.0;
        for (int i = 0; i < nocc_lr; ++i)
            for (int a = 0; a < nvirt_lr; ++a) {
                int idx = i * nvirt_lr + a;
                if (idx < static_cast<int>(X_I.size()))
                    val += X_I[idx] * R[i * nvirt_lr + a];
            }
        Sigma_lowdin(I, 0) = std::complex<double>(det_Soo * val, 0.0);
    }

    // 激发态→激发态:
    //   Σ_{IJ} = det(S^{oo}) × Σ_{ij} Soo_inv(j,i) × M^{IJ}_{ij}
    //   其中 M^{IJ}_{ij} = Σ_{ab} X^I_{ia} S̃_{ab} X^J_{jb}
    //
    // 优化: 先预计算 T^J_{ja} = Σ_b S̃_{ab} X^J_{jb}
    //        再 M^{IJ}_{ij} = Σ_a X^I_{ia} T^J_{ja}
    for (int J = 1; J < nstates_; ++J) {
        if (J >= static_cast<int>(casida_new.size())) continue;
        const auto& X_J = casida_new[J].X_coeffs;

        // T^J[j * nvirt_lr + a] = Σ_b S̃_{ab} X^J_{jb}
        std::vector<double> TJ(nocc_lr * nvirt_lr, 0.0);
        for (int j = 0; j < nocc_lr; ++j)
            for (int a = 0; a < nvirt_lr; ++a)
                for (int b = 0; b < nvirt_lr; ++b) {
                    int idx_jb = j * nvirt_lr + b;
                    if (idx_jb < static_cast<int>(X_J.size()))
                        TJ[j * nvirt_lr + a] += Stilde[a * nvirt_lr + b] * X_J[idx_jb];
                }

        for (int I = 1; I < nstates_; ++I) {
            if (I >= static_cast<int>(casida_old.size())) continue;
            const auto& X_I = casida_old[I].X_coeffs;

            // M^{IJ}_{ij} = Σ_a X^I_{ia} T^J_{ja}
            // Σ_{IJ} = det * Σ_{ij} Soo_inv(j,i) * M_{ij} + (Σ_{I0} * Σ_{0J}) / Σ_{00}
            double sigma_sum = 0.0;
            for (int i = 0; i < nocc_lr; ++i) {
                for (int j = 0; j < nocc_lr; ++j) {
                    double m_ij = 0.0;
                    for (int a = 0; a < nvirt_lr; ++a) {
                        int idx_ia = i * nvirt_lr + a;
                        if (idx_ia < static_cast<int>(X_I.size()))
                            m_ij += X_I[idx_ia] * TJ[j * nvirt_lr + a];
                    }
                    sigma_sum += Soo_inv(j, i) * m_ij;
                }
            }
            // Add the term (Σ_{I0} * Σ_{0J}) / Σ_{00} = det * val_I * val_J
            double term1 = (Sigma_lowdin(I, 0).real() * Sigma_lowdin(0, J).real()) / det_Soo;
            Sigma_lowdin(I, J) = std::complex<double>(det_Soo * sigma_sum + term1, 0.0);
        }
    }
}


// ====================================================================
// [FSSH修改说明] calculate_nac_from_dense 函数增加 use_tddft 参数
//
// 原代码:
//   void FsshDriver::calculate_nac_from_dense(coef_old, coef_new, s_ao_dense, sigma_out)
//   仅计算 KS 单粒子轨道之间的 NAC
//
// 修改原因:
//   当 use_tddft=true 时，FSSH 追踪的"态"不再是 KS 轨道，而是多体态
//   (基态 + TDA 激发态)，NAC 的计算方式完全不同:
//   - KS模式: 直接计算轨道重叠
//   - TDA模式: 先计算全轨道 MO 重叠，再用 Casida X 系数投影到多体态空间
//
// 数学公式详见 fssh_driver.h 中的注释
// ====================================================================
/// @brief Calculates the Non-Adiabatic Coupling (NAC) matrix using dense matrices.
/// @details
///   When use_tddft = false (KS mode):
///     S^{MO}_{ij} = C^†_i(t) · S^{AO} · C_j(t+Δt),  i,j ∈ [0, nstates_)
///     σ_{ij} = [S^{MO}_{ij} - (S^{MO}_{ji})*] / (2Δt)
///
///   When use_tddft = true (TDA mode):
///     Step 1: S^{MO}_{pq} = C^†_p(t) · S^{AO} · C_q(t+Δt),  p,q ∈ [0, nks_total_)
///     Step 2: Σ_{IJ} via Casida X coefficients (see below)
///     Step 3: σ^{TDA}_{IJ} = [Σ_{IJ} - (Σ_{JI})*] / (2Δt)
void FsshDriver::calculate_nac_from_dense(const ModuleBase::ComplexMatrix& coef_old,
                                          const ModuleBase::ComplexMatrix& coef_new,
                                          const ModuleBase::ComplexMatrix& s_ao_dense,
                                          ModuleBase::ComplexMatrix& sigma_out,
                                          bool use_tddft,
                                          const std::vector<CasidaWavefunction>& casida_old,
                                          const std::vector<CasidaWavefunction>& casida_new,
                                          std::vector<CasidaWavefunction>* casida_new_aligned_out) {

    // ====================================================================
    // TDA 多体态 NAC 分支 (方向 B: AO 空间直接计算)
    // ====================================================================
    //
    // 【方向 B 设计思想】
    //   旧方案 (方向 A): 先构造 MO 重叠矩阵 S^{MO}_{nks×nks}，再用 Casida X 系数
    //     投影到多体态空间。该方案受虚轨道混洗 (virtual orbital scrambling) 影响，
    //     需要额外的 MOM/SVD 修正。
    //
    //   新方案 (方向 B): 先将 Casida X 系数与 KS LCAO 系数收缩为 TDA 伪波函数
    //     C̃^I_{iμ} = Σ_a X^I_{ia} · C_{(nocc+a),μ}，再直接用 AO 重叠矩阵 S^{AO}
    //     计算多体态重叠 Σ_{IJ}。
    //     优势:
    //     - 完全绕过 MO 重叠矩阵，不受虚轨道混洗影响
    //     - 无需 SVD/MOM 修正
    //     - S^{AO} 是物理量，不依赖 MO 基变换
    //     - X 系数自动完成虚轨道子空间的收缩
    //
    // 【核心公式】
    //   Step 1: C̃^I_{iμ} = Σ_a X^I_{ia} · C_{(nocc+a), μ}
    //   Step 2: Σ_{IJ}(t, t') = Σ_i Σ_{μν} C̃^{I*}_{iμ}(t) · S^{AO}_{μν} · C̃^J_{iν}(t')
    //   Step 3: σ_{IJ} = [Σ_{IJ} - Σ*_{JI}] / (2Δt)
    //
    //   等价性证明:
    //     Σ_{IJ} = Σ_i Σ_{μν} [Σ_a X^I_{ia} C_{a+nocc,μ}(t)]* S^{AO}_{μν} [Σ_b X^J_{ib} C_{b+nocc,ν}(t')]
    //            = Σ_i Σ_{ab} X^I_{ia} [Σ_{μν} C*_{a+nocc,μ}(t) S^{AO}_{μν} C_{b+nocc,ν}(t')] X^J_{ib}
    //            = Σ_i Σ_{ab} X^I_{ia} · S^{MO}_{nocc+a, nocc+b} · X^J_{ib}
    //     与旧方案公式相同，但方向 B 不需要先构造 S^{MO}
    // ====================================================================
    if (use_tddft
        && !casida_old.empty() && !casida_new.empty()
        && nocc_ > 0 && nks_total_ > nocc_)
    {
        // [FSSH修改说明] 使用 LR 模块的 nocc_lr/nvirt_lr 代替 KS 的 nocc/nvirt
        // 原代码: const int nvirt = nks_total_ - nocc_;  // KS 虚轨道数
        // 问题: LR 模块可能只用部分占据/虚轨道 (由 INPUT 参数控制)
        //   X 系数布局为 X[i_lr * nvirt_lr + a_lr]，用 KS nvirt 索引会越界或错位
        // 修改后: 从 CasidaWavefunction 获取 LR 实际维度，并计算 KS 轨道偏移量
        //   LR 占据轨道 i_lr → KS 轨道 (nocc_ks - nocc_lr + i_lr) (取最高的 nocc_lr 个)
        //   LR 虚轨道 a_lr → KS 轨道 (nocc_ks + a_lr) (取最低的 nvirt_lr 个)
        int nocc_lr = 0, nvirt_lr = 0;
        if (casida_new.size() > 1) {
            nocc_lr = casida_new[1].nocc_lr;
            nvirt_lr = casida_new[1].nvirt_lr;
        }
        // 回退: 如果 LR 维度未设置，使用 KS 值
        if (nocc_lr <= 0) nocc_lr = nocc_;
        if (nvirt_lr <= 0) nvirt_lr = nks_total_ - nocc_;
        // KS 占据轨道偏移: LR 的第 i_lr 个占据轨道对应 KS 的第 i_ks 个
        const int occ_offset = nocc_ - nocc_lr;

        // ----------------------------------------------------------------
        // Step 1: 构造 TDA 伪波函数
        //   C̃^I_{i_lr, μ} = Σ_{a_lr} X^I_{i_lr, a_lr} · C_{(nocc_ks + a_lr), μ}
        //
        //   对每个激发态 I (I>0) 和每个 LR 占据轨道 i_lr:
        //     将所有 LR 虚轨道 LCAO 系数按 Casida X 系数做线性组合
        //
        //   数据结构: tda_wfc[I][i_lr] = vector<complex<double>>(nbasis_)
        //   注: casida_old/new 中 index 0 是基态 (X_coeffs 为空)
        // ----------------------------------------------------------------
        auto build_tda_pseudowfc = [&](
            const std::vector<CasidaWavefunction>& casida_wfcs,
            const ModuleBase::ComplexMatrix& coef)
        {
            // tda_wfc[I][i_lr][mu], I = 1..nstates_-1
            std::vector<std::vector<std::vector<std::complex<double>>>> tda_wfc(nstates_);
            for (int I = 1; I < nstates_; ++I) {
                tda_wfc[I].resize(nocc_lr, std::vector<std::complex<double>>(nbasis_, {0.0, 0.0}));
                if (I >= static_cast<int>(casida_wfcs.size())) continue;
                const auto& X_I = casida_wfcs[I].X_coeffs;
                for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
                    for (int a_lr = 0; a_lr < nvirt_lr; ++a_lr) {
                        int idx_ia = i_lr * nvirt_lr + a_lr;
                        if (idx_ia >= static_cast<int>(X_I.size())) continue;
                        int coef_row = nocc_ + a_lr;
                        if (coef_row >= coef.nr) continue; // 防止越界
                        double x_ia = X_I[idx_ia];
                        if (std::abs(x_ia) < 1e-15) continue;
                        // C̃^I_{i_lr, μ} += X^I_{i_lr, a_lr} · C_{(nocc_ks + a_lr), μ}
                        for (int mu = 0; mu < nbasis_; ++mu) {
                            tda_wfc[I][i_lr][mu] += x_ia * coef(coef_row, mu);
                        }
                    }
                }
            }
            return tda_wfc;
        };
        // 构造旧步 (t) 和新步 (t') 的 TDA 伪波函数
        auto tda_old = build_tda_pseudowfc(casida_old, coef_old);
        auto tda_new = build_tda_pseudowfc(casida_new, coef_new);

        // 调试: 检查伪波函数和原始数据的范数
        {
            int mpi_rank = 0;
            MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
            if (mpi_rank == 0) {
                std::ofstream diag("fssh_nac_diagnostic.log", std::ios::app);
                diag << std::scientific;
                diag << "=== TDA pseudowfc debug ===\n";
                diag << "  casida_old.size()=" << casida_old.size()
                     << " casida_new.size()=" << casida_new.size() << "\n";

                // X 系数信息
                for (int I = 1; I < nstates_ && I < static_cast<int>(casida_old.size()); ++I) {
                    const auto& Xo = casida_old[I].X_coeffs;
                    double norm2 = 0.0;
                    for (auto v : Xo) norm2 += v * v;
                    diag << "  casida_old[" << I << "]: X_size=" << Xo.size()
                         << " ||X||²=" << norm2 << "\n";
                }
                for (int I = 1; I < nstates_ && I < static_cast<int>(casida_new.size()); ++I) {
                    const auto& Xn = casida_new[I].X_coeffs;
                    double norm2 = 0.0;
                    for (auto v : Xn) norm2 += v * v;
                    diag << "  casida_new[" << I << "]: X_size=" << Xn.size()
                         << " ||X||²=" << norm2 << "\n";
                }

                // LR 维度信息
                diag << "  nocc_lr=" << nocc_lr << " nvirt_lr=" << nvirt_lr
                     << " occ_offset=" << occ_offset
                     << " nocc_ks=" << nocc_ << " nks_total=" << nks_total_
                     << " coef_old.nr=" << coef_old.nr << " coef_new.nr=" << coef_new.nr
                     << " max_virt_index(nocc_ks+nvirt_lr-1)=" << (nocc_ + nvirt_lr - 1) << "\n";

                // 伪波函数范数: ||C̃^I_i||² = Σ_μ |C̃^I_{iμ}|²
                for (int I = 1; I < nstates_ && I < static_cast<int>(tda_old.size()); ++I) {
                    double total_norm2 = 0.0;
                    for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
                        double n2 = 0.0;
                        for (int mu = 0; mu < nbasis_; ++mu) {
                            n2 += std::norm(tda_old[I][i_lr][mu]);
                        }
                        total_norm2 += n2;
                    }
                    diag << "  tda_old[" << I << "]: Σ_i||C̃||²=" << total_norm2 << "\n";
                }

                // coef 矩阵维度
                diag << "  coef_old dims: " << coef_old.nr << "x" << coef_old.nc << "\n";
                diag << "  coef_new dims: " << coef_new.nr << "x" << coef_new.nc << "\n";

                // coef 中虚轨道的范数
                for (int a = 0; a < std::min(nvirt_lr, 3); ++a) {
                    double n2 = 0.0;
                    for (int mu = 0; mu < nbasis_; ++mu) {
                        n2 += std::norm(coef_old(nocc_ + a, mu));
                    }
                    diag << "  ||coef_old(nocc+" << a << ",:)||²=" << n2 << "\n";
                }

                diag << "=== end pseudowfc debug ===\n";
                diag.close();
            }
        }

        // ----------------------------------------------------------------
        // Step 2: 计算多体态重叠矩阵 Σ_{IJ}(t, t')
        //   直接在 AO 空间计算，无需 MO 重叠矩阵
        //
        //   占据轨道 phase correction:
        //     计算 s^{occ}_{ii} = Σ_{μν} C*_{iμ}(t) S^{AO}_{μν} C_{iν}(t')
        //     如果对角元 < 0，翻转新步的对应符号
        // ----------------------------------------------------------------
        // [FSSH修改说明] phase correction 仅对 LR 参与的占据轨道
        // occ_phase[i_lr] 对应 KS 轨道 (occ_offset + i_lr)
        std::vector<double> occ_phase(nocc_lr, 1.0);
        for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
            int i_ks = occ_offset + i_lr;
            double s_ii = 0.0;
            for (int mu = 0; mu < nbasis_; ++mu) {
                for (int nu = 0; nu < nbasis_; ++nu) {
                    s_ii += (std::conj(coef_old(i_ks, mu)) * s_ao_dense(mu, nu) * coef_new(i_ks, nu)).real();
                }
            }
            if (s_ii < 0.0) occ_phase[i_lr] = -1.0;
        }

        // 构造 Sigma 矩阵
        ModuleBase::ComplexMatrix Sigma(nstates_, nstates_);

        for (int I = 0; I < nstates_; ++I) {
            for (int J = 0; J < nstates_; ++J) {
                std::complex<double> overlap(0.0, 0.0);

                if (I == 0 && J == 0) {
                    // 基态-基态: Σ_{00} ≈ 1
                    overlap = std::complex<double>(1.0, 0.0);
                }
                else if (I == 0 && J > 0) {
                    // 基态→激发态:
                    //   Σ_{0J} = Σ_{i_lr} Σ_{μν} C^{occ*}_{i_ks,μ}(t) · S^{AO}_{μν} · C̃^J_{i_lr,ν}(t')
                    // 相位说明:
                    //   occ_phase 来自新步占据轨道 C^{occ}(t') 的相位对齐，
                    //   仅应作用在显式包含 C^{occ}(t') 的项。
                    //   本项不含 C^{occ}(t')（只含 C^{occ}(t) 与 C^{virt}(t') 收缩得到的 C̃），
                    //   乘 occ_phase 会引入额外规范因子，导致 Σ_{0J} 号差并放大 NAC 偏差。
                    for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
                        int i_ks = occ_offset + i_lr;
                        for (int mu = 0; mu < nbasis_; ++mu) {
                            for (int nu = 0; nu < nbasis_; ++nu) {
                                overlap += std::conj(coef_old(i_ks, mu))
                                         * s_ao_dense(mu, nu)
                                         * tda_new[J][i_lr][nu];
                            }
                        }
                    }
                }
                else if (I > 0 && J == 0) {
                    // 激发态→基态:
                    //   Σ_{I0} = Σ_{i_lr} Σ_{μν} C̃^{I*}_{i_lr,μ}(t) · S^{AO}_{μν} · C^{occ}_{i_ks,ν}(t')
                    // 该项显式包含新步占据轨道 C^{occ}(t')，需保留 occ_phase 修正。
                    for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
                        int i_ks = occ_offset + i_lr;
                        for (int mu = 0; mu < nbasis_; ++mu) {
                            for (int nu = 0; nu < nbasis_; ++nu) {
                                overlap += std::conj(tda_old[I][i_lr][mu])
                                         * s_ao_dense(mu, nu)
                                         * coef_new(i_ks, nu) * occ_phase[i_lr];
                            }
                        }
                    }
                }
                else { // I > 0 && J > 0
                    // 激发态-激发态 (核心公式):
                    //   Σ_{IJ} = Σ_{i_lr} Σ_{μν} C̃^{I*}_{i_lr,μ}(t) · S^{AO}_{μν} · C̃^J_{i_lr,ν}(t')
                    for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) {
                        for (int mu = 0; mu < nbasis_; ++mu) {
                            for (int nu = 0; nu < nbasis_; ++nu) {
                                overlap += std::conj(tda_old[I][i_lr][mu])
                                         * s_ao_dense(mu, nu)
                                         * tda_new[J][i_lr][nu];
                            }
                        }
                    }
                }

                Sigma(I, J) = overlap;
            }
        }
        // 方向 B (对角近似) 的 Sigma 保存为 Sigma_approx
        ModuleBase::ComplexMatrix Sigma_approx(Sigma);

        // ================================================================
        // Löwdin 精确 CIS 重叠计算
        // ================================================================
        ModuleBase::ComplexMatrix Sigma_lowdin(nstates_, nstates_);
        double det_Soo = 1.0;
        this->compute_lowdin_sigma(coef_old, coef_new, s_ao_dense,
                                   casida_old, casida_new,
                                   nocc_lr, nvirt_lr, occ_offset,
                                   occ_phase, Sigma_lowdin, &det_Soo);

        // 用 Löwdin Sigma 替换主 Sigma (后续相位修正和 NAC 输出将基于此)
        for (int I = 0; I < nstates_; ++I)
            for (int J = 0; J < nstates_; ++J)
                Sigma(I, J) = Sigma_lowdin(I, J);

        // ================================================================
        // 诊断输出: Sigma 矩阵基本性质 (两种方法对比)
        // ================================================================
        {
            int mpi_rank = 0;
            MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
            if (mpi_rank == 0)
            {
                std::ofstream diag("fssh_nac_diagnostic.log", std::ios::app);
                diag << std::scientific;
                diag << "============================================\n";
                diag << "FSSH NAC Diagnostic (TDA branch - Lowdin + AO-approx)\n";
                diag << "  nocc_ks=" << nocc_ << " nks_total=" << nks_total_
                     << " nocc_lr=" << nocc_lr << " nvirt_lr=" << nvirt_lr
                     << " occ_offset=" << occ_offset
                     << " nbasis=" << nbasis_ << " nstates=" << nstates_ << "\n";
                diag << "  det(S^oo) = " << det_Soo << "\n";

                // 占据轨道 phase 修正信息
                diag << "  Occupied orbital phase signs (LR orbitals): ";
                for (int i_lr = 0; i_lr < nocc_lr; ++i_lr) diag << occ_phase[i_lr] << " ";
                diag << "\n";

                // Sigma 对角元对比
                diag << "  Sigma diagonal (Lowdin): ";
                for (int I = 0; I < nstates_; ++I)
                    diag << Sigma_lowdin(I, I).real() << " ";
                diag << "\n";
                diag << "  Sigma diagonal (approx): ";
                for (int I = 0; I < nstates_; ++I)
                    diag << Sigma_approx(I, I).real() << " ";
                diag << "\n";

                // 完整 Sigma 矩阵 (Löwdin，用于相位修正)
                diag << "  Sigma matrix [Lowdin] (before phase correction):\n";
                for (int I = 0; I < nstates_; ++I) {
                    diag << "    ";
                    for (int J = 0; J < nstates_; ++J) {
                        diag << "(" << Sigma_lowdin(I, J).real() << ","
                             << Sigma_lowdin(I, J).imag() << ") ";
                    }
                    diag << "\n";
                }

                diag << "============================================\n";
                diag.close();
            }
        }

        // ================================================================
        // [FSSH修改说明] 激发态相位校正 + 简并态子空间对齐
        //
        // 问题背景:
        //   LR-TDDFT 求解器返回的激发态本征向量 X 具有任意的全局相位 (X 与 -X
        //   是同一物理态), 不同时间步的相位选择是独立随机的, 导致:
        //
        //   (1) 非简并相位翻转: |Σ_{JJ}| ≈ 1 但 Σ_{JJ} < 0
        //       例: State 1 在 t 时为 +X, 在 t' 时为 -X, 则 Σ_{11} = -1
        //
        //   (2) 简并子空间旋转: 当两态 J, K 近简并时, LR 求解器在子空间内的
        //       本征向量方向是任意的, 导致 |Σ_{JJ}| ≈ 0 但 |Σ_{JK}| ≈ 1
        //       (态标签在 t 与 t' 之间发生交换/旋转)
        //
        // 修正方法:
        //   (1) 相位修正: 对每个激发态 J, 若 Σ_{JJ} < 0 且 |Σ_{JJ}| 大于阈值,
        //       将 Sigma 的第 J 列乘以 -1 (等价于翻转新步态 J 的符号)
        //
        //   (2) 简并对齐: 对 |Σ_{JJ}| 小的激发态, 寻找与之强耦合的另一态 K
        //       (|Σ_{JK}| 大), 在 (J, K) 子空间内右乘 2×2 块的转置:
        //         M = [[Σ_JJ, Σ_JK], [Σ_KJ, Σ_KK]] (近似正交矩阵)
        //         W = M^T (对正交 M 等价于 M^{-1})
        //         Σ_corrected = Σ · W (右乘, 仅作用于第 J 和 K 列)
        //       修正后 Σ_corrected(J,J) ≈ 1, Σ_corrected(K,K) ≈ 1
        //
        // 注: 这两个修正不影响基态 (I=0, J=0), 仅作用于激发态子空间.
        //     反对称化 σ_{IJ} = [Σ_{IJ} - Σ*_{JI}]/(2Δt) 在校正后的 Sigma 上进行,
        //     得到的 NAC 反映物理上正确的多体态间耦合.
        // ================================================================
        // ----------------------------------------------------------------
        // 通用 n×n SVD-based Procrustes 对齐
        //
        // 数学原理:
        //   设 LR 求解器在 t' 给出的本征基与 t 时刻的连续基之间相差一个未知酉矩阵 U:
        //     |Ψ_J^solver(t')⟩ = Σ_K U_{KJ} |Ψ_K^continuous(t')⟩
        //   对小 Δt, 连续基缓变, 故 Σ_{IJ} = ⟨Ψ_I(t)|Ψ_J^solver(t')⟩ ≈ U_{IJ}
        //
        //   要把 solver 基拉回连续基, 需对 Σ 右乘 W 使 Σ·W ≈ I (在被混合的子空间内).
        //   最优正交 W 由 Procrustes 求解: minimize ||M·W - I||_F over orthogonal W
        //   等价于 minimize ||M - W^T||_F → W^T = closest_orthogonal(M)
        //   对 M = U_sv · S · V_sv^T 做 SVD, 最近正交矩阵为 P = U_sv · V_sv^T,
        //   故 W = P^T = V_sv · U_sv^T.
        //
        //   非简并相位翻转是此公式 m=1 的特例: M = [-1] → W = [-1] (列乘 -1).
        //
        // 算法:
        //   1. 在 [1, nstates_) 上构造无向图: 边 (J,K) 当 max(|Σ_JK|,|Σ_KJ|) > thr
        //   2. 找连通分量. 单点分量 (size=1): 仅做相位翻转.
        //                  多点分量 (size≥2): 提取 m×m 子块做 SVD-Procrustes.
        //   3. 同步把相同的变换应用到 casida_new 的 X 系数 (供 cache)
        // ----------------------------------------------------------------
        const double phase_threshold = 0.2;

        // --- Step 1: 构造耦合图并找连通分量 ---
        // off_strong[J][K] = true 表示 J,K (J,K≥1) 之间存在强耦合
        std::vector<std::vector<bool>> adj(nstates_, std::vector<bool>(nstates_, false));
        for (int J = 1; J < nstates_; ++J) {
            for (int K = J + 1; K < nstates_; ++K) {
                double off = std::max(std::abs(Sigma(J, K).real()),
                                      std::abs(Sigma(K, J).real()));
                if (off > phase_threshold) {
                    adj[J][K] = adj[K][J] = true;
                }
            }
        }

        // 连通分量 (BFS)
        std::vector<int> component(nstates_, -1);  // 每个态所属分量 id
        std::vector<std::vector<int>> groups;       // groups[g] = 该分量的态列表
        for (int J = 1; J < nstates_; ++J) {
            if (component[J] != -1) continue;
            int gid = static_cast<int>(groups.size());
            groups.emplace_back();
            // BFS
            std::vector<int> queue = {J};
            component[J] = gid;
            for (size_t qi = 0; qi < queue.size(); ++qi) {
                int u = queue[qi];
                groups[gid].push_back(u);
                for (int v = 1; v < nstates_; ++v) {
                    if (component[v] == -1 && adj[u][v]) {
                        component[v] = gid;
                        queue.push_back(v);
                    }
                }
            }
            std::sort(groups[gid].begin(), groups[gid].end());
        }

        // --- Step 2: 对每个分量计算正交修正矩阵 W (相对于该分量) ---
        // 整体修正矩阵为块对角: W_full = blockdiag({W_g}). I=0 (基态) 不变.
        // 我们以 (excited_signs, group_W) 两种形式记录, 后面统一应用到 Sigma 和 X.
        std::vector<int> excited_signs(nstates_, 1);  // 单点分量使用
        // group_corr[g] = m×m 修正矩阵 W (行主序 m×m), 仅对 m≥2 分量
        std::vector<std::vector<double>> group_corr(groups.size());
        std::vector<std::vector<int>> degenerate_groups_diag;  // 用于诊断输出

        for (size_t g = 0; g < groups.size(); ++g) {
            const auto& grp = groups[g];
            const int m = static_cast<int>(grp.size());

            if (m == 1) {
                // 单点分量: 只做相位翻转
                int J = grp[0];
                double diag_val = Sigma(J, J).real();
                if (diag_val < 0.0) {
                    excited_signs[J] = -1;
                }
                // 注: 若 |diag_val| 很小但又无强耦合, 说明该态在 t→t' 间几乎完全
                //   失去重叠 (可能跑出 nstate 截断之外), 此时无可靠的修正方法,
                //   保持原样并由后续诊断输出报警.
            } else {
                // 多点分量: 做 m×m SVD-Procrustes
                // 提取子块 M_{ab} = Sigma(grp[a], grp[b]).real() (LR 系数为实数)
                // LAPACK 列主序: M_cm[a + b*m] = M(a,b)
                std::vector<double> M_cm(m * m);
                for (int a = 0; a < m; ++a) {
                    for (int b = 0; b < m; ++b) {
                        M_cm[a + b * m] = Sigma(grp[a], grp[b]).real();
                    }
                }

                std::vector<double> U_sv(m * m), VT_sv(m * m), sing(m);
                int info = 0, lwork = -1;
                double wquery;
                int mm = m;
                // workspace 查询
                dgesvd_("A", "A", &mm, &mm, M_cm.data(), &mm,
                        sing.data(), U_sv.data(), &mm, VT_sv.data(), &mm,
                        &wquery, &lwork, &info);
                lwork = static_cast<int>(wquery) + 1;
                std::vector<double> work(lwork);
                // 注意: dgesvd 会破坏 M_cm, 但我们已不再需要它
                dgesvd_("A", "A", &mm, &mm, M_cm.data(), &mm,
                        sing.data(), U_sv.data(), &mm, VT_sv.data(), &mm,
                        work.data(), &lwork, &info);

                if (info != 0) {
                    // SVD 失败: 退化为对角符号修正 (兜底)
                    for (int a = 0; a < m; ++a) {
                        int J = grp[a];
                        if (Sigma(J, J).real() < 0.0) excited_signs[J] = -1;
                    }
                    continue;
                }

                // Procrustes 最近正交: P = U · V^T (列主序: P[a+c*m] = Σ_k U[a+k*m]·VT[k+c*m])
                // 我们要的修正 W = P^T = V · U^T
                // 行主序存储 W[a*m + b] = (V·U^T)_{ab} = Σ_k V_{ak} U_{bk}
                //                       = Σ_k VT_{ka} · U_{bk}      (V_{ak}=VT_{ka})
                //                       = Σ_k VT_cm[k+a*m] · U_cm[b+k*m]
                std::vector<double>& W = group_corr[g];
                W.assign(m * m, 0.0);
                for (int a = 0; a < m; ++a) {
                    for (int b = 0; b < m; ++b) {
                        double s = 0.0;
                        for (int k = 0; k < m; ++k) {
                            s += VT_sv[k + a * m] * U_sv[b + k * m];
                        }
                        W[a * m + b] = s;
                    }
                }
                degenerate_groups_diag.push_back(grp);
            }
        }

        // --- Step 3: 把 W (相位 + 旋转) 应用到 Sigma 和 Sigma_approx 的列 ---
        // 注: 相位修正基于 Sigma (= Löwdin)，但同一修正也应用到 Sigma_approx
        //     以保持两者在相同规范下，便于公平对比
        // 对单点分量 J: Sigma(:, J) *= excited_signs[J]
        // 对多点分量 grp[]: 旧列副本 -> 新列 = Σ_b W[a,b] * 旧列_{grp[b]}?
        //   注意定义: Σ_corr(I, grp[a]) = Σ_b Σ(I, grp[b]) · W_{ba}
        //   这里 W 是修正矩阵 (右乘), 元素 W_{ba} = (V·U^T)_{ba}
        for (int J = 1; J < nstates_; ++J) {
            if (excited_signs[J] == -1) {
                for (int I = 0; I < nstates_; ++I) {
                    Sigma(I, J) *= -1.0;
                    Sigma_approx(I, J) *= -1.0;
                }
            }
        }
        for (size_t g = 0; g < groups.size(); ++g) {
            const auto& grp = groups[g];
            const int m = static_cast<int>(grp.size());
            if (m < 2) continue;
            const std::vector<double>& W = group_corr[g];

            // 备份旧列 (Sigma = Löwdin)
            std::vector<std::vector<std::complex<double>>> old_cols(
                m, std::vector<std::complex<double>>(nstates_));
            std::vector<std::vector<std::complex<double>>> old_cols_approx(
                m, std::vector<std::complex<double>>(nstates_));
            for (int b = 0; b < m; ++b) {
                for (int I = 0; I < nstates_; ++I) {
                    old_cols[b][I] = Sigma(I, grp[b]);
                    old_cols_approx[b][I] = Sigma_approx(I, grp[b]);
                }
            }
            // 写入新列: Σ(:, grp[a]) = Σ_b old_cols[b] · W[b,a]
            for (int a = 0; a < m; ++a) {
                int Ja = grp[a];
                for (int I = 0; I < nstates_; ++I) {
                    std::complex<double> s(0.0, 0.0), s_approx(0.0, 0.0);
                    for (int b = 0; b < m; ++b) {
                        s += old_cols[b][I] * W[b * m + a];
                        s_approx += old_cols_approx[b][I] * W[b * m + a];
                    }
                    Sigma(I, Ja) = s;
                    Sigma_approx(I, Ja) = s_approx;
                }
            }
        }

        // --- Step 4: 同步 W 到 casida_new 的 X 系数, 输出对齐版本供 cache ---
        // 物理意义: 我们对 t' 步的态做了基矢变换 |Ψ_J^aligned⟩ = Σ_K W_{KJ} |Ψ_K^solver⟩
        // 对应 X 系数: X^{J,aligned}_{ia} = Σ_K W_{KJ} · X^{K,solver}_{ia}
        // 单点分量是 m=1 的特例 (W=[±1]).
        // 注: casida_new 与 Sigma 使用相同的索引约定:
        //   casida_new[0] 是基态占位符 (X_coeffs 为空), casida_new[1..nstates_-1] 是激发态.
        //   因此态索引 J 直接对应 casida_new[J], 无需 -1 偏移.
        if (casida_new_aligned_out != nullptr) {
            *casida_new_aligned_out = casida_new;  // 拷贝, 然后就地修改
            auto& aligned = *casida_new_aligned_out;
            const int n_aligned = static_cast<int>(aligned.size());

            // 单点相位翻转
            for (int J = 1; J < nstates_; ++J) {
                if (excited_signs[J] != -1) continue;
                if (J >= n_aligned) continue;
                for (auto& x : aligned[J].X_coeffs) x = -x;
                for (auto& y : aligned[J].Y_coeffs) y = -y;
            }

            // 多点分量旋转
            for (size_t g = 0; g < groups.size(); ++g) {
                const auto& grp = groups[g];
                const int m = static_cast<int>(grp.size());
                if (m < 2) continue;
                const std::vector<double>& W = group_corr[g];
                if (static_cast<int>(W.size()) != m * m) continue;  // SVD 失败时 W 为空, 跳过

                // 收集分量内 X (深拷贝旧值)
                std::vector<std::vector<double>> old_X(m), old_Y(m);
                bool ok = true;
                for (int b = 0; b < m; ++b) {
                    int idx = grp[b];
                    if (idx < 0 || idx >= n_aligned) { ok = false; break; }
                    old_X[b] = aligned[idx].X_coeffs;
                    old_Y[b] = aligned[idx].Y_coeffs;
                }
                if (!ok) continue;

                // 写入新 X^{aligned, grp[a]} = Σ_b W[b,a] · old_X[b]
                for (int a = 0; a < m; ++a) {
                    int idx = grp[a];
                    auto& Xnew = aligned[idx].X_coeffs;
                    auto& Ynew = aligned[idx].Y_coeffs;
                    std::fill(Xnew.begin(), Xnew.end(), 0.0);
                    std::fill(Ynew.begin(), Ynew.end(), 0.0);
                    for (int b = 0; b < m; ++b) {
                        double w_ba = W[b * m + a];
                        for (size_t k = 0; k < Xnew.size() && k < old_X[b].size(); ++k)
                            Xnew[k] += w_ba * old_X[b][k];
                        for (size_t k = 0; k < Ynew.size() && k < old_Y[b].size(); ++k)
                            Ynew[k] += w_ba * old_Y[b][k];
                    }
                }
            }
        }

        // 诊断输出: 相位修正和简并对齐
        {
            int mpi_rank = 0;
            MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
            if (mpi_rank == 0)
            {
                std::ofstream diag("fssh_nac_diagnostic.log", std::ios::app);
                diag << std::scientific;
                diag << "  Phase correction signs (excited states 1.." << (nstates_-1) << "): ";
                for (int J = 1; J < nstates_; ++J) diag << excited_signs[J] << " ";
                diag << "\n";
                if (!degenerate_groups_diag.empty()) {
                    diag << "  Degenerate groups aligned via SVD-Procrustes (size>=2):\n";
                    for (const auto& grp : degenerate_groups_diag) {
                        diag << "    {";
                        for (size_t i = 0; i < grp.size(); ++i) {
                            diag << grp[i] << (i + 1 < grp.size() ? "," : "");
                        }
                        diag << "} (m=" << grp.size() << ")\n";
                    }
                }
                diag << "  Sigma diagonal AFTER correction: ";
                for (int I = 0; I < nstates_; ++I) {
                    diag << Sigma(I, I).real() << " ";
                }
                diag << "\n";
                diag.close();
            }
        }

        // ----------------------------------------------------------------
        // Step 3: 反对称化得到 TDA NAC
        //   sigma_out 使用 Löwdin Sigma (驱动电子方程演化)
        //   sigma_approx_nac 使用对角近似 Sigma (仅供对比)
        //   σ^{TDA}_{IJ} = [Σ_{IJ} - (Σ_{JI})*] / (2Δt)
        // ----------------------------------------------------------------
        ModuleBase::ComplexMatrix sigma_approx_nac(nstates_, nstates_);
        for (int I = 0; I < nstates_; ++I) {
            for (int J = 0; J < nstates_; ++J) {
                sigma_out(I, J) = (Sigma(I, J) - std::conj(Sigma(J, I))) / (2.0 * dt_);
                sigma_approx_nac(I, J) = (Sigma_approx(I, J) - std::conj(Sigma_approx(J, I))) / (2.0 * dt_);
            }
        }

        // ================================================================
        // 输出 Löwdin vs 对角近似 对比 log
        // ================================================================
        {
            int mpi_rank = 0;
            MPI_Comm_rank(MPI_COMM_WORLD, &mpi_rank);
            if (mpi_rank == 0)
            {
                // --- 1. 在原有诊断 log 中输出 NAC 矩阵 ---
                {
                    std::ofstream diag("fssh_nac_diagnostic.log", std::ios::app);
                    diag << std::scientific;
                    diag << "  NAC sigma matrix [Lowdin] (1/a.u.):\n";
                    for (int I = 0; I < nstates_; ++I) {
                        diag << "    ";
                        for (int J = 0; J < nstates_; ++J) {
                            diag << "(" << sigma_out(I, J).real() << ","
                                 << sigma_out(I, J).imag() << ") ";
                        }
                        diag << "\n";
                    }
                    diag << "\n";
                    diag.close();
                }

                // --- 2. 专用对比 log: fssh_lowdin_comparison.log ---
                {
                    std::ofstream cmp("fssh_lowdin_comparison.log", std::ios::app);
                    cmp << std::scientific;
                    cmp << "========================================================\n";
                    cmp << "  Lowdin vs Diagonal-Approx Comparison\n";
                    cmp << "  det(S^oo) = " << det_Soo << "\n";
                    cmp << "  nocc_lr=" << nocc_lr << " nvirt_lr=" << nvirt_lr
                        << " nstates=" << nstates_ << " dt=" << dt_ << "\n";
                    cmp << "--------------------------------------------------------\n";

                    // Sigma 矩阵对比 (相位修正后)
                    cmp << "  Sigma matrix comparison (after phase correction):\n";
                    double max_sigma_diff = 0.0;
                    for (int I = 0; I < nstates_; ++I) {
                        for (int J = 0; J < nstates_; ++J) {
                            double diff = std::abs(Sigma(I, J) - Sigma_approx(I, J));
                            if (diff > max_sigma_diff) max_sigma_diff = diff;
                            cmp << "    Sigma(" << I << "," << J << "): "
                                << "Lowdin=" << Sigma(I, J).real()
                                << "  Approx=" << Sigma_approx(I, J).real()
                                << "  Diff=" << diff << "\n";
                        }
                    }
                    cmp << "  max |Sigma_lowdin - Sigma_approx| = " << max_sigma_diff << "\n";
                    cmp << "--------------------------------------------------------\n";

                    // NAC 矩阵对比
                    cmp << "  NAC sigma comparison (1/a.u.):\n";
                    double max_nac_diff = 0.0;
                    for (int I = 0; I < nstates_; ++I) {
                        for (int J = 0; J < nstates_; ++J) {
                            double diff = std::abs(sigma_out(I, J) - sigma_approx_nac(I, J));
                            if (diff > max_nac_diff) max_nac_diff = diff;
                            cmp << "    NAC(" << I << "," << J << "): "
                                << "Lowdin=(" << sigma_out(I, J).real()
                                << "," << sigma_out(I, J).imag() << ")  "
                                << "Approx=(" << sigma_approx_nac(I, J).real()
                                << "," << sigma_approx_nac(I, J).imag() << ")  "
                                << "Diff=" << diff << "\n";
                        }
                    }
                    cmp << "  max |NAC_lowdin - NAC_approx| = " << max_nac_diff << "\n";

                    // 对角元偏差 (Sigma 对角元应接近 1)
                    cmp << "--------------------------------------------------------\n";
                    cmp << "  Sigma diagonal deviation from 1:\n";
                    for (int I = 0; I < nstates_; ++I) {
                        cmp << "    State " << I << ": "
                            << "Lowdin=" << (Sigma(I, I).real() - 1.0)
                            << "  Approx=" << (Sigma_approx(I, I).real() - 1.0) << "\n";
                    }

                    cmp << "========================================================\n\n";
                    cmp.close();
                }
            }
        }

        return; // TDA 分支完成，跳过 KS 分支

    }

    // ====================================================================
    // KS 单粒子轨道 NAC 分支 (原始代码，未修改)
    // 当 use_tddft=false 或 Casida 数据不可用时使用
    // ====================================================================
    ModuleBase::ComplexMatrix s_mo(nstates_, nstates_);

    // 1. Calculate the overlap in the molecular orbital (MO) basis
    for (int i = 0; i < nstates_; ++i) {
        for (int j = 0; j < nstates_; ++j) {
            std::complex<double> sum(0.0, 0.0);
            for (int mu = 0; mu < nbasis_; ++mu) {
                for (int nu = 0; nu < nbasis_; ++nu) {
                    sum += std::conj(coef_old(i, mu)) * s_ao_dense(mu, nu) * coef_new(j, nu);
                }
            }
            s_mo(i, j) = sum;
        }
    }

    // 2. Phase Tracking (Phase Alignment)
    // Corrects random sign flips introduced by independent SCF diagonalizations.
    for (int j = 0; j < nstates_; ++j) {
        if (s_mo(j, j).real() < 0.0) {
            for (int i = 0; i < nstates_; ++i) {
                s_mo(i, j) = -s_mo(i, j);
            }
        }
    }

    // 3. Calculate Non-Adiabatic Coupling elements
    for (int i = 0; i < nstates_; ++i) {
        for (int j = 0; j < nstates_; ++j) {
            sigma_out(i, j) = (s_mo(i, j) - std::conj(s_mo(j, i))) / (2.0 * dt_);
        }
    }

}

/// @brief Computes the time derivative of the electronic wave function coefficients.
std::vector<std::complex<double>> FsshDriver::compute_derivative(
    const std::vector<std::complex<double>>& coeffs,
    const std::vector<double>& energies,
    const ModuleBase::ComplexMatrix& sigma) {
    
    std::vector<std::complex<double>> d_coeffs(nstates_, std::complex<double>(0.0, 0.0));
    const std::complex<double> I(0.0, 1.0);
    
    // Planck constant (hbar) is 1.0 in atomic units. 
    // Equation: dc_k/dt = -i * E_k * c_k - sum_j (sigma_kj * c_j)
    for (int k = 0; k < nstates_; ++k) {
        // Convert energy units to atomic units if necessary.
        // Assuming 'energies' are properly scaled or hbar matches the energy units.
        d_coeffs[k] = -I * energies[k] * coeffs[k];
        for (int j = 0; j < nstates_; ++j) {
            d_coeffs[k] -= sigma(k, j) * coeffs[j];
        }
    }
    return d_coeffs;
}

/// @brief Propagates the electronic amplitudes using the 4th-order Runge-Kutta method.
void FsshDriver::propagate_rk4(const ModuleBase::ComplexMatrix& sigma,
                               const std::vector<double>& energies) {
    // Utilize micro-steps for stable electronic integration
    const int num_sub_steps = 100;
    const double dt_sub = dt_ / static_cast<double>(num_sub_steps);

    for (int step = 0; step < num_sub_steps; ++step) {
        std::vector<std::complex<double>> k1 = this->compute_derivative(electronic_coeffs_, energies, sigma);

        std::vector<std::complex<double>> temp_c(nstates_);
        for (int i = 0; i < nstates_; ++i) {
            temp_c[i] = electronic_coeffs_[i] + 0.5 * dt_sub * k1[i];
        }
        std::vector<std::complex<double>> k2 = this->compute_derivative(temp_c, energies, sigma);

        for (int i = 0; i < nstates_; ++i) {
            temp_c[i] = electronic_coeffs_[i] + 0.5 * dt_sub * k2[i];
        }
        std::vector<std::complex<double>> k3 = this->compute_derivative(temp_c, energies, sigma);

        for (int i = 0; i < nstates_; ++i) {
            temp_c[i] = electronic_coeffs_[i] + dt_sub * k3[i];
        }
        std::vector<std::complex<double>> k4 = this->compute_derivative(temp_c, energies, sigma);

        double norm_sq = 0.0;
        for (int i = 0; i < nstates_; ++i) {
            electronic_coeffs_[i] += (dt_sub / 6.0) * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]);
            norm_sq += std::norm(electronic_coeffs_[i]);
        }

        // Enforce norm conservation strictly to prevent numerical drift
        double norm = std::sqrt(norm_sq);
        for (int i = 0; i < nstates_; ++i) {
            electronic_coeffs_[i] /= norm;
        }
    }
}

/// @brief Determines the target state for a potential surface hop.
int FsshDriver::check_hopping(const ModuleBase::ComplexMatrix& sigma) {
    std::vector<double> hop_probs(nstates_, 0.0);
    double current_pop = std::norm(electronic_coeffs_[current_state_]);

    // Calculate fewest-switches hopping probabilities
    for (int k = 0; k < nstates_; ++k) {
        if (k == current_state_) {
            continue;
        }
        
        // g_jk = 2 * dt * Re(c_j^* c_k sigma_jk) / |c_j|^2
        double b_jk = 2.0 * (std::conj(electronic_coeffs_[current_state_]) * electronic_coeffs_[k] * sigma(current_state_, k)).real();
                             
        double prob = b_jk * dt_ / current_pop;
        hop_probs[k] = std::max(0.0, prob); // Negative probabilities are strictly zeroed
    }

    // Synchronize random number generation across all MPI ranks
    int my_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

    double zeta = 0.0;
    if (my_rank == 0) {
        zeta = rand_dist_(gen_);
    }
    MPI_Bcast(&zeta, 1, MPI_DOUBLE, 0, MPI_COMM_WORLD);

    // Evaluate surface hopping threshold
    double accumulated_prob = 0.0;
    int proposed_state = current_state_;

    for (int k = 0; k < nstates_; ++k) {
        if (k == current_state_) {
            continue;
        }
        accumulated_prob += hop_probs[k];
        if (zeta < accumulated_prob) {
            proposed_state = k;
            break;
        }
    }

    return proposed_state;
}

/// @brief Validates energy conservation and rescales nuclear velocities if a hop occurs.
bool FsshDriver::rescale_velocity(UnitCell& ucell, int old_state, int new_state, const std::vector<double>& energies) {
    // Physical constants for unit conversion
    const double AMU_TO_ME = 1822.888486;   // 1 AMU in electron mass
    const double HARTREE_TO_RY = 2.0;       // 1 Hartree in Rydberg

    double kinetic_energy_ry = 0.0;

    // Calculate total kinetic energy in Rydberg
    for (int it = 0; it < ucell.ntype; ++it) {
        double mass_amu = ucell.atoms[it].mass;
        for (int ia = 0; ia < ucell.atoms[it].na; ++ia) {
            double vx = ucell.atoms[it].vel[ia].x;
            double vy = ucell.atoms[it].vel[ia].y;
            double vz = ucell.atoms[it].vel[ia].z;

            double ke_hartree = 0.5 * (mass_amu * AMU_TO_ME) * (vx * vx + vy * vy + vz * vz);
            kinetic_energy_ry += ke_hartree * HARTREE_TO_RY;
        }
    }

    // Energy gap between the target state and the current state
    double de_ry = energies[new_state] - energies[old_state];

    int my_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

    if (kinetic_energy_ry < de_ry) {
        // Frustrated hop: Not enough kinetic energy to overcome the energy gap
        if (my_rank == 0) {
            std::cout << "[FSSH INFO] Frustrated hop detected. Insufficient kinetic energy. Hop rejected." << std::endl;
        }
        return false;
    } else {
        // Successful hop: Rescale velocities uniformly to conserve total energy
        // (Note: For a more rigorous approach, velocities should be rescaled along the NAC vector)
        double scale_factor = std::sqrt((kinetic_energy_ry - de_ry) / kinetic_energy_ry);

        for (int it = 0; it < ucell.ntype; ++it) {
            for (int ia = 0; ia < ucell.atoms[it].na; ++ia) {
                ucell.atoms[it].vel[ia].x *= scale_factor;
                ucell.atoms[it].vel[ia].y *= scale_factor;
                ucell.atoms[it].vel[ia].z *= scale_factor;
            }
        }
        return true;
    }
}

int FsshDriver::run_step_advanced(const ModuleBase::ComplexMatrix& coef_old,
                                  const ModuleBase::ComplexMatrix& coef_new,
                                  const std::string& csr_file,
                                  const std::vector<double>& energies,
                                  UnitCell& ucell,
                                  bool use_tddft,
                                  const std::vector<double>& tddft_energies,
                                  const std::vector<CasidaWavefunction>& casida_wfcs) {
    
    // Determine the active energy baseline (KS vs TDDFT)
    std::vector<double> active_energies = energies;
    if (use_tddft && tddft_energies.size() >= nstates_) {
        active_energies = tddft_energies;
    }

    ModuleBase::ComplexMatrix s_ao = this->parse_latest_csr(csr_file);
    ModuleBase::ComplexMatrix sigma(nstates_, nstates_);

    // [FSSH修改说明] NAC 计算传入 use_tddft 参数和 Casida 波函数数据
    // 原代码:
    //   this->calculate_nac_from_dense(coef_old, coef_new, s_ao, sigma);
    // 修改原因: 当 use_tddft=true 时，使用 TDA 伪波函数的 NAC 替代 KS 轨道 NAC
    //   casida_wfcs_old_ 缓存了上一步的 Casida 数据，casida_wfcs 是当前步的数据
    //   若 casida_wfcs_old_ 为空 (首次调用)，函数内部自动回退到 KS NAC
    // [FSSH修改说明] 缓存对齐后的 casida_new 而非原始 LR 求解器输出
    // 物理意义: calculate_nac_from_dense 内部对 t' 步的多体态做了相位翻转和
    //   简并子空间旋转, 把 LR 求解器随机选取的本征基对齐到 t 步的连续基.
    //   传播得到的电子系数 c_I(t') 是在这个 *对齐后* 的基矢规范下的振幅.
    //   下一步 (t' → t'') 计算 NAC 时, 必须用对齐后的 X^I(t') 作为 "old",
    //   否则 c_I 与基矢规范错位, 跃迁概率 P_{IJ} = 2Re(c*_I c_J σ_{JI})Δt 会
    //   累积相位/旋转误差.
    std::vector<CasidaWavefunction> casida_aligned;
    this->calculate_nac_from_dense(coef_old, coef_new, s_ao, sigma,
                                   use_tddft, casida_wfcs_old_, casida_wfcs,
                                   &casida_aligned);

    // 缓存对齐后的 Casida 数据供下一步使用 (保持基矢规范的时间连续性)
    if (use_tddft && !casida_wfcs.empty()) {
        casida_wfcs_old_ = casida_aligned.empty() ? casida_wfcs : casida_aligned;
    }

    this->propagate_rk4(sigma, active_energies);

    int my_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);

    std::vector<std::complex<double>> c_dot = this->compute_derivative(electronic_coeffs_, active_energies, sigma);

    // Rank 0 handles file I/O to avoid race conditions
    if (my_rank == 0) {
        static std::ofstream debug_ofs("fssh_debug_details.csv", std::ios::app);
        static int debug_step = 0;
        debug_step++;

        if (debug_step == 1) {
            debug_ofs << "Step";
            for (int i = 0; i < nstates_; ++i) debug_ofs << ",Pop_" << i;
            for (int i = 0; i < nstates_; ++i) debug_ofs << ",dPop" << i << "_dt";
            for (int i = 0; i < nstates_; ++i) {
                for (int j = i + 1; j < nstates_; ++j) {
                    debug_ofs << ",NAC_" << i << "_" << j << "_Re";
                }
            }
            debug_ofs << "\n";
        }

        debug_ofs << debug_step;
        for (int i = 0; i < nstates_; ++i) {
            debug_ofs << "," << std::fixed << std::setprecision(8) << std::norm(electronic_coeffs_[i]);
        }
        for (int i = 0; i < nstates_; ++i) {
            double dpop_i_dt = 2.0 * (std::conj(electronic_coeffs_[i]) * c_dot[i]).real();
            debug_ofs << "," << std::fixed << std::setprecision(8) << dpop_i_dt;
        }
        for (int i = 0; i < nstates_; ++i) {
            for (int j = i + 1; j < nstates_; ++j) {
                debug_ofs << "," << std::fixed << std::setprecision(8) << sigma(i, j).real();
            }
        }
        debug_ofs << "\n";
        debug_ofs.flush();
    }

    int proposed_state = this->check_hopping(sigma);

    if (proposed_state != current_state_) {
        bool success = this->rescale_velocity(ucell, current_state_, proposed_state, active_energies);
        if (success) {
            if (my_rank == 0) {
                std::cout << "[FSSH] Hop Executed: State " << current_state_ 
                          << " -> " << proposed_state << std::endl;
            }
            current_state_ = proposed_state;
            return proposed_state;
        }
    }
    return current_state_;
}

