# In compatibility to builtin FindLAPACK.cmake before v3.5.4
if(DEFINED LAPACK_DIR)
  string(APPEND CMAKE_PREFIX_PATH ";${LAPACK_DIR}")
endif()
if(DEFINED LAPACK_LIBRARY)
  set(LAPACK_LIBRARIES ${LAPACK_LIBRARY})
endif()

find_package(Blas REQUIRED)
find_package(LAPACK REQUIRED)

find_path(LAPACKE_INCLUDE_DIR
  NAMES lapacke.h
  PATHS ${LAPACK_DIR} ${LAPACKE_DIR} ${CMAKE_PREFIX_PATH}
  PATH_SUFFIXES include include/lapacke
  DOC "Path to LAPACKE include directory"
)
# find LAPACKE libraries
find_library(LAPACKE_LIBRARY
  NAMES lapacke
  PATHS ${LAPACK_DIR} ${LAPACK_LIBRARIES} ${CMAKE_PREFIX_PATH}
  PATH_SUFFIXES lib lib64
  DOC "Path to LAPACKE library"
)

if(NOT TARGET LAPACKE::LAPACKE)
  add_library(LAPACKE::LAPACKE UNKNOWN IMPORTED)
  set_target_properties(LAPACKE::LAPACKE PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LAPACKE_INCLUDE_DIR}"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    IMPORTED_LOCATION "${LAPACKE_LIBRARY}")
endif()
