/**
 * @file xc_functional_libxc_id.cpp
 * this file stores the IDs of the XC functionals
 * 
 * libxc version: 7.0.0
 */
#include <vector>
#include <map>
#include <string>

#include "module_base/tool_quit.h"
#include "module_hamilt_general/module_xc/xc_functional_libxc.h"

const std::map<std::string, int> mymap_xcname_xcid = {
    {"LDA_X_1D_EXPONENTIAL", 600},
    {"LDA_X_1D_SOFT", 21},
    {"LDA_X_2D", 19},
    {"LDA_X_ERF", 546},
    {"LDA_X_RAE", 549},
    {"LDA_X_REL", 532},
    {"LDA_X_SLOC", 692},
    {"LDA_X_YUKAWA", 641},
    {"LDA_C_1D_CSC", 18},
    {"LDA_C_1D_LOOS", 26},
    {"LDA_C_2D_AMGB", 15},
    {"LDA_C_2D_PRM", 16},
    {"LDA_C_BR78", 552},
    {"LDA_C_CHACHIYO", 287},
    {"LDA_C_CHACHIYO_MOD", 307},
    {"LDA_C_EPC17", 328},
    {"LDA_C_EPC17_2", 329},
    {"LDA_C_EPC18_1", 330},
    {"LDA_C_EPC18_2", 331},
    {"LDA_C_GK72", 578},
    {"LDA_C_GL", 5},
    {"LDA_C_GOMBAS", 24},
    {"LDA_C_HL", 4},
    {"LDA_C_KARASIEV", 579},
    {"LDA_C_KARASIEV_MOD", 308},
    {"LDA_C_LP96", 289},
    {"LDA_C_MCWEENY", 551},
    {"LDA_C_ML1", 22},
    {"LDA_C_ML2", 23},
    {"LDA_C_OB_PW", 14},
    {"LDA_C_OB_PZ", 11},
    {"LDA_C_OW", 574},
    {"LDA_C_OW_LYP", 573},
    {"LDA_C_PK09", 554},
    {"LDA_C_PMGB06", 590},
    {"LDA_C_PW", 12},
    {"LDA_C_PW_ERF", 654},
    {"LDA_C_PW_MOD", 13},
    {"LDA_C_PW_RPA", 25},
    {"LDA_C_PZ", 9},
    {"LDA_C_PZ_MOD", 10},
    {"LDA_C_RC04", 27},
    {"LDA_C_RPA", 3},
    {"LDA_C_RPW92", 684},
    {"LDA_C_UPW92", 683},
    {"LDA_C_VBH", 17},
    {"LDA_C_VWN", 7},
    {"LDA_C_VWN_1", 28},
    {"LDA_C_VWN_2", 29},
    {"LDA_C_VWN_3", 30},
    {"LDA_C_VWN_4", 31},
    {"LDA_C_VWN_RPA", 8},
    {"LDA_C_W20", 317},
    {"LDA_C_WIGNER", 2},
    {"LDA_C_XALPHA", 6},
    {"LDA_XC_1D_EHWLRG_1", 536},
    {"LDA_XC_1D_EHWLRG_2", 537},
    {"LDA_XC_1D_EHWLRG_3", 538},
    {"LDA_XC_CORRKSDT", 318},
    {"LDA_XC_GDSMFB", 577},
    {"LDA_XC_KSDT", 259},
    {"LDA_XC_LP_A", 547},
    {"LDA_XC_LP_B", 548},
    {"LDA_XC_TETER93", 20},
    {"LDA_XC_TIH", 599},
    {"LDA_XC_ZLP", 43},
    {"GGA_X_2D_B86", 128},
    {"GGA_X_2D_B86_MGC", 124},
    {"GGA_X_2D_B88", 127},
    {"GGA_X_2D_PBE", 129},
    {"GGA_X_AIRY", 192},
    {"GGA_X_AK13", 56},
    {"GGA_X_AM05", 120},
    {"GGA_X_APBE", 184},
    {"GGA_X_B86", 103},
    {"GGA_X_B86_MGC", 105},
    {"GGA_X_B86_R", 41},
    {"GGA_X_B88", 106},
    {"GGA_X_B88_6311G", 179},
    {"GGA_X_B88M", 570},
    {"GGA_X_BAYESIAN", 125},
    {"GGA_X_BCGP", 38},
    {"GGA_X_BEEFVDW", 285},
    {"GGA_X_BKL1", 338},
    {"GGA_X_BKL2", 339},
    {"GGA_X_BPCCAC", 98},
    {"GGA_X_C09X", 158},
    {"GGA_X_CAP", 270},
    {"GGA_X_CHACHIYO", 298},
    {"GGA_X_DK87_R1", 111},
    {"GGA_X_DK87_R2", 112},
    {"GGA_X_EB88", 271},
    {"GGA_X_ECMV92", 215},
    {"GGA_X_EV93", 35},
    {"GGA_X_FD_LB94", 604},
    {"GGA_X_FD_REVLB94", 605},
    {"GGA_X_FT97_A", 114},
    {"GGA_X_FT97_B", 115},
    {"GGA_X_G96", 107},
    {"GGA_X_GAM", 32},
    {"GGA_X_GG99", 535},
    {"GGA_X_HCTH_A", 34},
    {"GGA_X_HJS_B88", 527},
    {"GGA_X_HJS_B88_V2", 46},
    {"GGA_X_HJS_B97X", 528},
    {"GGA_X_HJS_PBE", 525},
    {"GGA_X_HJS_PBE_SOL", 526},
    {"GGA_X_HTBS", 191},
    {"GGA_X_ITYH", 529},
    {"GGA_X_ITYH_OPTX", 622},
    {"GGA_X_ITYH_PBE", 623},
    {"GGA_X_KGG99", 544},
    {"GGA_X_KT1", 145},
    {"GGA_X_LAG", 193},
    {"GGA_X_LAMBDA_CH_N", 44},
    {"GGA_X_LAMBDA_LO_N", 45},
    {"GGA_X_LAMBDA_OC2_N", 40},
    {"GGA_X_LB", 160},
    {"GGA_X_LBM", 182},
    {"GGA_X_LG93", 113},
    {"GGA_X_LSPBE", 168},
    {"GGA_X_LSRPBE", 169},
    {"GGA_X_LV_RPW86", 58},
    {"GGA_X_MB88", 149},
    {"GGA_X_MPBE", 122},
    {"GGA_X_MPW91", 119},
    {"GGA_X_N12", 82},
    {"GGA_X_NCAP", 180},
    {"GGA_X_NCAPR", 324},
    {"GGA_X_OL2", 183},
    {"GGA_X_OPTB86B_VDW", 171},
    {"GGA_X_OPTB88_VDW", 139},
    {"GGA_X_OPTPBE_VDW", 141},
    {"GGA_X_OPTX", 110},
    {"GGA_X_PBE", 101},
    {"GGA_X_PBE_ERF_GWS", 655},
    {"GGA_X_PBE_GAUSSIAN", 321},
    {"GGA_X_PBE_JSJR", 126},
    {"GGA_X_PBE_MOD", 320},
    {"GGA_X_PBE_MOL", 49},
    {"GGA_X_PBE_R", 102},
    {"GGA_X_PBE_SOL", 116},
    {"GGA_X_PBE_TCA", 59},
    {"GGA_X_PBEA", 121},
    {"GGA_X_PBEFE", 265},
    {"GGA_X_PBEINT", 60},
    {"GGA_X_PBEK1_VDW", 140},
    {"GGA_X_PBEPOW", 539},
    {"GGA_X_PBETRANS", 291},
    {"GGA_X_PW86", 108},
    {"GGA_X_PW91", 109},
    {"GGA_X_PW91_MOD", 316},
    {"GGA_X_Q1D", 734},
    {"GGA_X_Q2D", 48},
    {"GGA_X_REVSSB_D", 312},
    {"GGA_X_RGE2", 142},
    {"GGA_X_RPBE", 117},
    {"GGA_X_RPW86", 144},
    {"GGA_X_S12G", 495},
    {"GGA_X_SFAT", 530},
    {"GGA_X_SFAT_PBE", 601},
    {"GGA_X_SG4", 533},
    {"GGA_X_SOGGA", 150},
    {"GGA_X_SOGGA11", 151},
    {"GGA_X_SSB", 91},
    {"GGA_X_SSB_D", 92},
    {"GGA_X_SSB_SW", 90},
    {"GGA_X_VMT84_GE", 68},
    {"GGA_X_VMT84_PBE", 69},
    {"GGA_X_VMT_GE", 70},
    {"GGA_X_VMT_PBE", 71},
    {"GGA_X_WC", 118},
    {"GGA_X_WPBEH", 524},
    {"GGA_X_XPBE", 123},
    {"GGA_C_ACGGA", 39},
    {"GGA_C_ACGGAP", 176},
    {"GGA_C_AM05", 135},
    {"GGA_C_APBE", 186},
    {"GGA_C_BMK", 280},
    {"GGA_C_CCDF", 313},
    {"GGA_C_CHACHIYO", 309},
    {"GGA_C_CS1", 565},
    {"GGA_C_FT97", 88},
    {"GGA_C_GAM", 33},
    {"GGA_C_GAPC", 555},
    {"GGA_C_GAPLOC", 556},
    {"GGA_C_HCTH_A", 97},
    {"GGA_C_HYB_TAU_HCTH", 283},
    {"GGA_C_LM", 137},
    {"GGA_C_LYP", 131},
    {"GGA_C_LYPR", 624},
    {"GGA_C_MGGAC", 712},
    {"GGA_C_N12", 80},
    {"GGA_C_N12_SX", 79},
    {"GGA_C_OP_B88", 87},
    {"GGA_C_OP_G96", 85},
    {"GGA_C_OP_PBE", 86},
    {"GGA_C_OP_PW91", 262},
    {"GGA_C_OP_XALPHA", 84},
    {"GGA_C_OPTC", 200},
    {"GGA_C_P86", 132},
    {"GGA_C_P86_FT", 217},
    {"GGA_C_P86VWN", 252},
    {"GGA_C_P86VWN_FT", 253},
    {"GGA_C_PBE", 130},
    {"GGA_C_PBE_ERF_GWS", 657},
    {"GGA_C_PBE_GAUSSIAN", 322},
    {"GGA_C_PBE_JRGX", 138},
    {"GGA_C_PBE_MOL", 272},
    {"GGA_C_PBE_SOL", 133},
    {"GGA_C_PBE_VWN", 216},
    {"GGA_C_PBEFE", 258},
    {"GGA_C_PBEINT", 62},
    {"GGA_C_PBELOC", 246},
    {"GGA_C_PW91", 134},
    {"GGA_C_Q2D", 47},
    {"GGA_C_REGTPSS", 83},
    {"GGA_C_REVTCA", 99},
    {"GGA_C_RGE2", 143},
    {"GGA_C_SCAN_E0", 553},
    {"GGA_C_SG4", 534},
    {"GGA_C_SOGGA11", 152},
    {"GGA_C_SOGGA11_X", 159},
    {"GGA_C_SPBE", 89},
    {"GGA_C_TAU_HCTH", 281},
    {"GGA_C_TCA", 100},
    {"GGA_C_TM_LYP", 559},
    {"GGA_C_TM_PBE", 560},
    {"GGA_C_W94", 561},
    {"GGA_C_WI", 148},
    {"GGA_C_WI0", 153},
    {"GGA_C_WL", 147},
    {"GGA_C_XPBE", 136},
    {"GGA_C_ZPBEINT", 61},
    {"GGA_C_ZPBESOL", 63},
    {"GGA_C_ZVPBEINT", 557},
    {"GGA_C_ZVPBELOC", 606},
    {"GGA_C_ZVPBESOL", 558},
    {"GGA_XC_B97_3C", 327},
    {"GGA_XC_B97_D", 170},
    {"GGA_XC_B97_GGA1", 96},
    {"GGA_XC_BEEFVDW", 286},
    {"GGA_XC_EDF1", 165},
    {"GGA_XC_HCTH_120", 162},
    {"GGA_XC_HCTH_147", 163},
    {"GGA_XC_HCTH_407", 164},
    {"GGA_XC_HCTH_407P", 93},
    {"GGA_XC_HCTH_93", 161},
    {"GGA_XC_HCTH_P14", 95},
    {"GGA_XC_HCTH_P76", 94},
    {"GGA_XC_HLE16", 545},
    {"GGA_XC_KT1", 167},
    {"GGA_XC_KT2", 146},
    {"GGA_XC_KT3", 587},
    {"GGA_XC_MOHLYP", 194},
    {"GGA_XC_MOHLYP2", 195},
    {"GGA_XC_MPWLYP1W", 174},
    {"GGA_XC_NCAP", 181},
    {"GGA_XC_OBLYP_D", 67},
    {"GGA_XC_OPBE_D", 65},
    {"GGA_XC_OPWLYP_D", 66},
    {"GGA_XC_PBE1W", 173},
    {"GGA_XC_PBELYP1W", 175},
    {"GGA_XC_TH1", 154},
    {"GGA_XC_TH2", 155},
    {"GGA_XC_TH3", 156},
    {"GGA_XC_TH4", 157},
    {"GGA_XC_TH_FC", 197},
    {"GGA_XC_TH_FCFO", 198},
    {"GGA_XC_TH_FCO", 199},
    {"GGA_XC_TH_FL", 196},
    {"GGA_XC_VV10", 255},
    {"GGA_XC_XLYP", 166},
    {"HYB_GGA_X_CAM_S12G", 646},
    {"HYB_GGA_X_CAM_S12H", 647},
    {"HYB_GGA_X_N12_SX", 81},
    {"HYB_GGA_X_PBE_ERF_GWS", 656},
    {"HYB_GGA_X_S12H", 496},
    {"HYB_GGA_X_SOGGA11_X", 426},
    {"HYB_GGA_XC_APBE0", 607},
    {"HYB_GGA_XC_APF", 409},
    {"HYB_GGA_XC_B1LYP", 416},
    {"HYB_GGA_XC_B1PW91", 417},
    {"HYB_GGA_XC_B1WC", 412},
    {"HYB_GGA_XC_B3LYP", 402},
    {"HYB_GGA_XC_B3LYP3", 394},
    {"HYB_GGA_XC_B3LYP5", 475},
    {"HYB_GGA_XC_B3LYP_MCM1", 461},
    {"HYB_GGA_XC_B3LYP_MCM2", 462},
    {"HYB_GGA_XC_B3LYPS", 459},
    {"HYB_GGA_XC_B3P86", 403},
    {"HYB_GGA_XC_B3P86_NWCHEM", 315},
    {"HYB_GGA_XC_B3PW91", 401},
    {"HYB_GGA_XC_B5050LYP", 572},
    {"HYB_GGA_XC_B97", 407},
    {"HYB_GGA_XC_B97_1", 408},
    {"HYB_GGA_XC_B97_1P", 266},
    {"HYB_GGA_XC_B97_2", 410},
    {"HYB_GGA_XC_B97_3", 414},
    {"HYB_GGA_XC_B97_K", 413},
    {"HYB_GGA_XC_BHANDH", 435},
    {"HYB_GGA_XC_BHANDHLYP", 436},
    {"HYB_GGA_XC_BLYP35", 499},
    {"HYB_GGA_XC_CAM_B3LYP", 433},
    {"HYB_GGA_XC_CAM_O3LYP", 395},
    {"HYB_GGA_XC_CAM_PBEH", 681},
    {"HYB_GGA_XC_CAM_QTP_00", 490},
    {"HYB_GGA_XC_CAM_QTP_01", 482},
    {"HYB_GGA_XC_CAM_QTP_02", 491},
    {"HYB_GGA_XC_CAMH_B3LYP", 614},
    {"HYB_GGA_XC_CAMY_B3LYP", 470},
    {"HYB_GGA_XC_CAMY_BLYP", 455},
    {"HYB_GGA_XC_CAMY_PBEH", 682},
    {"HYB_GGA_XC_CAP0", 477},
    {"HYB_GGA_XC_CASE21", 390},
    {"HYB_GGA_XC_EDF2", 476},
    {"HYB_GGA_XC_HAPBE", 608},
    {"HYB_GGA_XC_HFLYP", 314},
    {"HYB_GGA_XC_HJS_B88", 431},
    {"HYB_GGA_XC_HJS_B97X", 432},
    {"HYB_GGA_XC_HJS_PBE", 429},
    {"HYB_GGA_XC_HJS_PBE_SOL", 430},
    {"HYB_GGA_XC_HPBEINT", 472},
    {"HYB_GGA_XC_HSE03", 427},
    {"HYB_GGA_XC_HSE06", 428},
    {"HYB_GGA_XC_HSE12", 479},
    {"HYB_GGA_XC_HSE12S", 480},
    {"HYB_GGA_XC_HSE_SOL", 481},
    {"HYB_GGA_XC_KMLYP", 485},
    {"HYB_GGA_XC_LB07", 589},
    {"HYB_GGA_XC_LC_BLYP", 400},
    {"HYB_GGA_XC_LC_BLYP_EA", 625},
    {"HYB_GGA_XC_LC_BLYPR", 639},
    {"HYB_GGA_XC_LC_BOP", 636},
    {"HYB_GGA_XC_LC_PBEOP", 637},
    {"HYB_GGA_XC_LC_QTP", 492},
    {"HYB_GGA_XC_LC_VV10", 469},
    {"HYB_GGA_XC_LC_WPBE", 478},
    {"HYB_GGA_XC_LC_WPBE08_WHS", 488},
    {"HYB_GGA_XC_LC_WPBE_WHS", 486},
    {"HYB_GGA_XC_LC_WPBEH_WHS", 487},
    {"HYB_GGA_XC_LC_WPBESOL_WHS", 489},
    {"HYB_GGA_XC_LCY_BLYP", 468},
    {"HYB_GGA_XC_LCY_PBE", 467},
    {"HYB_GGA_XC_LRC_WPBE", 473},
    {"HYB_GGA_XC_LRC_WPBEH", 465},
    {"HYB_GGA_XC_MB3LYP_RC04", 437},
    {"HYB_GGA_XC_MCAM_B3LYP", 640},
    {"HYB_GGA_XC_MPW1K", 405},
    {"HYB_GGA_XC_MPW1LYP", 483},
    {"HYB_GGA_XC_MPW1PBE", 484},
    {"HYB_GGA_XC_MPW1PW", 418},
    {"HYB_GGA_XC_MPW3LYP", 419},
    {"HYB_GGA_XC_MPW3PW", 415},
    {"HYB_GGA_XC_MPWLYP1M", 453},
    {"HYB_GGA_XC_O3LYP", 404},
    {"HYB_GGA_XC_OPB3LYP", 386},
    {"HYB_GGA_XC_PBE0_13", 456},
    {"HYB_GGA_XC_PBE38", 393},
    {"HYB_GGA_XC_PBE50", 290},
    {"HYB_GGA_XC_PBE_2X", 392},
    {"HYB_GGA_XC_PBE_MOL0", 273},
    {"HYB_GGA_XC_PBE_MOLB0", 276},
    {"HYB_GGA_XC_PBE_SOL0", 274},
    {"HYB_GGA_XC_PBEB0", 275},
    {"HYB_GGA_XC_PBEH", 406},
    {"HYB_GGA_XC_QTP17", 460},
    {"HYB_GGA_XC_RCAM_B3LYP", 610},
    {"HYB_GGA_XC_RELPBE0", 325},
    {"HYB_GGA_XC_REVB3LYP", 454},
    {"HYB_GGA_XC_SB98_1A", 420},
    {"HYB_GGA_XC_SB98_1B", 421},
    {"HYB_GGA_XC_SB98_1C", 422},
    {"HYB_GGA_XC_SB98_2A", 423},
    {"HYB_GGA_XC_SB98_2B", 424},
    {"HYB_GGA_XC_SB98_2C", 425},
    {"HYB_GGA_XC_TUNED_CAM_B3LYP", 434},
    {"HYB_GGA_XC_WB97", 463},
    {"HYB_GGA_XC_WB97X", 464},
    {"HYB_GGA_XC_WB97X_D", 471},
    {"HYB_GGA_XC_WB97X_D3", 399},
    {"HYB_GGA_XC_WB97X_V", 466},
    {"HYB_GGA_XC_WC04", 611},
    {"HYB_GGA_XC_WHPBE0", 615},
    {"HYB_GGA_XC_WP04", 612},
    {"HYB_GGA_XC_X3LYP", 411},
    {"MGGA_X_2D_JS17", 609},
    {"MGGA_X_2D_PRHG07", 210},
    {"MGGA_X_2D_PRHG07_PRP10", 211},
    {"MGGA_X_B00", 284},
    {"MGGA_X_BJ06", 207},
    {"MGGA_X_BLOC", 244},
    {"MGGA_X_BR89", 206},
    {"MGGA_X_BR89_1", 214},
    {"MGGA_X_BR89_EXPLICIT", 586},
    {"MGGA_X_BR89_EXPLICIT_1", 602},
    {"MGGA_X_EDMGGA", 686},
    {"MGGA_X_EEL", 326},
    {"MGGA_X_FT98", 319},
    {"MGGA_X_GDME_0", 689},
    {"MGGA_X_GDME_KOS", 690},
    {"MGGA_X_GDME_NV", 687},
    {"MGGA_X_GDME_VT", 691},
    {"MGGA_X_GVT4", 204},
    {"MGGA_X_GX", 575},
    {"MGGA_X_HLTA", 698},
    {"MGGA_X_JK", 256},
    {"MGGA_X_KTBM_0", 735},
    {"MGGA_X_KTBM_1", 736},
    {"MGGA_X_KTBM_10", 745},
    {"MGGA_X_KTBM_11", 746},
    {"MGGA_X_KTBM_12", 747},
    {"MGGA_X_KTBM_13", 748},
    {"MGGA_X_KTBM_14", 749},
    {"MGGA_X_KTBM_15", 750},
    {"MGGA_X_KTBM_16", 751},
    {"MGGA_X_KTBM_17", 752},
    {"MGGA_X_KTBM_18", 753},
    {"MGGA_X_KTBM_19", 754},
    {"MGGA_X_KTBM_2", 737},
    {"MGGA_X_KTBM_20", 755},
    {"MGGA_X_KTBM_21", 756},
    {"MGGA_X_KTBM_22", 757},
    {"MGGA_X_KTBM_23", 758},
    {"MGGA_X_KTBM_24", 759},
    {"MGGA_X_KTBM_3", 738},
    {"MGGA_X_KTBM_4", 739},
    {"MGGA_X_KTBM_5", 740},
    {"MGGA_X_KTBM_6", 741},
    {"MGGA_X_KTBM_7", 742},
    {"MGGA_X_KTBM_8", 743},
    {"MGGA_X_KTBM_9", 744},
    {"MGGA_X_KTBM_GAP", 760},
    {"MGGA_X_LAK", 342},
    {"MGGA_X_LTA", 201},
    {"MGGA_X_M06_L", 203},
    {"MGGA_X_M11_L", 226},
    {"MGGA_X_MBEEF", 249},
    {"MGGA_X_MBEEFVDW", 250},
    {"MGGA_X_MBR", 716},
    {"MGGA_X_MBRXC_BG", 696},
    {"MGGA_X_MBRXH_BG", 697},
    {"MGGA_X_MCML", 644},
    {"MGGA_X_MGGAC", 711},
    {"MGGA_X_MK00", 230},
    {"MGGA_X_MK00B", 243},
    {"MGGA_X_MN12_L", 227},
    {"MGGA_X_MN15_L", 260},
    {"MGGA_X_MODTPSS", 245},
    {"MGGA_X_MS0", 221},
    {"MGGA_X_MS1", 222},
    {"MGGA_X_MS2", 223},
    {"MGGA_X_MS2_REV", 228},
    {"MGGA_X_MS2B", 300},
    {"MGGA_X_MS2BS", 301},
    {"MGGA_X_MSB86BL", 765},
    {"MGGA_X_MSPBEL", 761},
    {"MGGA_X_MSRPBEL", 763},
    {"MGGA_X_MTASK", 724},
    {"MGGA_X_MVS", 257},
    {"MGGA_X_MVSB", 302},
    {"MGGA_X_MVSBS", 303},
    {"MGGA_X_PBE_GX", 576},
    {"MGGA_X_PKZB", 213},
    {"MGGA_X_R2SCAN", 497},
    {"MGGA_X_R2SCAN01", 645},
    {"MGGA_X_R2SCANL", 718},
    {"MGGA_X_R4SCAN", 650},
    {"MGGA_X_REGTM", 626},
    {"MGGA_X_REGTPSS", 603},
    {"MGGA_X_REVM06_L", 293},
    {"MGGA_X_REVSCAN", 581},
    {"MGGA_X_REVSCANL", 701},
    {"MGGA_X_REVTM", 693},
    {"MGGA_X_REVTPSS", 212},
    {"MGGA_X_RLDA", 688},
    {"MGGA_X_RMSB86BL", 766},
    {"MGGA_X_RMSPBEL", 762},
    {"MGGA_X_RMSRPBEL", 764},
    {"MGGA_X_RPP09", 209},
    {"MGGA_X_RPPSCAN", 648},
    {"MGGA_X_RSCAN", 493},
    {"MGGA_X_RTPSS", 299},
    {"MGGA_X_SA_TPSS", 542},
    {"MGGA_X_SCAN", 263},
    {"MGGA_X_SCANL", 700},
    {"MGGA_X_TASK", 707},
    {"MGGA_X_TAU_HCTH", 205},
    {"MGGA_X_TB09", 208},
    {"MGGA_X_TH", 225},
    {"MGGA_X_TLDA", 685},
    {"MGGA_X_TM", 540},
    {"MGGA_X_TPSS", 202},
    {"MGGA_X_VCML", 651},
    {"MGGA_X_VT84", 541},
    {"MGGA_C_B88", 571},
    {"MGGA_C_B94", 397},
    {"MGGA_C_BC95", 240},
    {"MGGA_C_CC", 387},
    {"MGGA_C_CCALDA", 388},
    {"MGGA_C_CF22D", 341},
    {"MGGA_C_CS", 72},
    {"MGGA_C_DLDF", 37},
    {"MGGA_C_HLTAPW", 699},
    {"MGGA_C_KCIS", 562},
    {"MGGA_C_KCISK", 638},
    {"MGGA_C_M05", 237},
    {"MGGA_C_M05_2X", 238},
    {"MGGA_C_M06", 235},
    {"MGGA_C_M06_2X", 236},
    {"MGGA_C_M06_HF", 234},
    {"MGGA_C_M06_L", 233},
    {"MGGA_C_M06_SX", 311},
    {"MGGA_C_M08_HX", 78},
    {"MGGA_C_M08_SO", 77},
    {"MGGA_C_M11", 76},
    {"MGGA_C_M11_L", 75},
    {"MGGA_C_MN12_L", 74},
    {"MGGA_C_MN12_SX", 73},
    {"MGGA_C_MN15", 269},
    {"MGGA_C_MN15_L", 261},
    {"MGGA_C_PKZB", 239},
    {"MGGA_C_R2SCAN", 498},
    {"MGGA_C_R2SCAN01", 642},
    {"MGGA_C_R2SCANL", 719},
    {"MGGA_C_REVM06", 306},
    {"MGGA_C_REVM06_L", 294},
    {"MGGA_C_REVM11", 172},
    {"MGGA_C_REVSCAN", 582},
    {"MGGA_C_REVSCAN_VV10", 585},
    {"MGGA_C_REVTM", 694},
    {"MGGA_C_REVTPSS", 241},
    {"MGGA_C_RMGGAC", 643},
    {"MGGA_C_RPPSCAN", 649},
    {"MGGA_C_RREGTM", 391},
    {"MGGA_C_RSCAN", 494},
    {"MGGA_C_SCAN", 267},
    {"MGGA_C_SCAN_RVV10", 292},
    {"MGGA_C_SCAN_VV10", 584},
    {"MGGA_C_SCANL", 702},
    {"MGGA_C_SCANL_RVV10", 703},
    {"MGGA_C_SCANL_VV10", 704},
    {"MGGA_C_TM", 251},
    {"MGGA_C_TPSS", 231},
    {"MGGA_C_TPSS_GAUSSIAN", 323},
    {"MGGA_C_TPSSLOC", 247},
    {"MGGA_C_VSXC", 232},
    {"MGGA_XC_B97M_V", 254},
    {"MGGA_XC_CC06", 229},
    {"MGGA_XC_HLE17", 288},
    {"MGGA_XC_LP90", 564},
    {"MGGA_XC_OTPSS_D", 64},
    {"MGGA_XC_TPSSLYP1W", 242},
    {"MGGA_XC_VCML_RVV10", 652},
    {"MGGA_XC_ZLP", 42},
    {"HYB_MGGA_X_BMK", 279},
    {"HYB_MGGA_X_CF22D", 340},
    {"HYB_MGGA_X_DLDF", 36},
    {"HYB_MGGA_X_JS18", 705},
    {"HYB_MGGA_X_M05", 438},
    {"HYB_MGGA_X_M05_2X", 439},
    {"HYB_MGGA_X_M06", 449},
    {"HYB_MGGA_X_M06_2X", 450},
    {"HYB_MGGA_X_M06_HF", 444},
    {"HYB_MGGA_X_M06_SX", 310},
    {"HYB_MGGA_X_M08_HX", 295},
    {"HYB_MGGA_X_M08_SO", 296},
    {"HYB_MGGA_X_M11", 297},
    {"HYB_MGGA_X_MN12_SX", 248},
    {"HYB_MGGA_X_MN15", 268},
    {"HYB_MGGA_X_MS2H", 224},
    {"HYB_MGGA_X_MVSH", 474},
    {"HYB_MGGA_X_PJS18", 706},
    {"HYB_MGGA_X_REVM06", 305},
    {"HYB_MGGA_X_REVM11", 304},
    {"HYB_MGGA_X_REVSCAN0", 583},
    {"HYB_MGGA_X_SCAN0", 264},
    {"HYB_MGGA_X_TAU_HCTH", 282},
    {"HYB_MGGA_XC_B0KCIS", 563},
    {"HYB_MGGA_XC_B86B95", 441},
    {"HYB_MGGA_XC_B88B95", 440},
    {"HYB_MGGA_XC_B94_HYB", 398},
    {"HYB_MGGA_XC_B98", 598},
    {"HYB_MGGA_XC_BB1K", 443},
    {"HYB_MGGA_XC_BR3P86", 389},
    {"HYB_MGGA_XC_EDMGGAH", 695},
    {"HYB_MGGA_XC_GAS22", 658},
    {"HYB_MGGA_XC_LC_TMLYP", 720},
    {"HYB_MGGA_XC_MPW1B95", 445},
    {"HYB_MGGA_XC_MPW1KCIS", 566},
    {"HYB_MGGA_XC_MPWB1K", 446},
    {"HYB_MGGA_XC_MPWKCIS1K", 567},
    {"HYB_MGGA_XC_PBE1KCIS", 568},
    {"HYB_MGGA_XC_PW6B95", 451},
    {"HYB_MGGA_XC_PW86B95", 442},
    {"HYB_MGGA_XC_PWB6K", 452},
    {"HYB_MGGA_XC_R2SCAN0", 660},
    {"HYB_MGGA_XC_R2SCAN50", 661},
    {"HYB_MGGA_XC_R2SCANH", 659},
    {"HYB_MGGA_XC_REVTPSSH", 458},
    {"HYB_MGGA_XC_TPSS0", 396},
    {"HYB_MGGA_XC_TPSS1KCIS", 569},
    {"HYB_MGGA_XC_TPSSH", 457},
    {"HYB_MGGA_XC_WB97M_V", 531},
    {"HYB_MGGA_XC_X1B95", 447},
    {"HYB_MGGA_XC_XB1K", 448}
};

const std::vector<std::string> mymap_xcid_xcname = {
    "__unknown__",
    "__unknown__",
    "LDA_C_WIGNER",
    "LDA_C_RPA",
    "LDA_C_HL",
    "LDA_C_GL",
    "LDA_C_XALPHA",
    "LDA_C_VWN",
    "LDA_C_VWN_RPA",
    "LDA_C_PZ",
    "LDA_C_PZ_MOD",
    "LDA_C_OB_PZ",
    "LDA_C_PW",
    "LDA_C_PW_MOD",
    "LDA_C_OB_PW",
    "LDA_C_2D_AMGB",
    "LDA_C_2D_PRM",
    "LDA_C_VBH",
    "LDA_C_1D_CSC",
    "LDA_X_2D",
    "LDA_XC_TETER93",
    "LDA_X_1D_SOFT",
    "LDA_C_ML1",
    "LDA_C_ML2",
    "LDA_C_GOMBAS",
    "LDA_C_PW_RPA",
    "LDA_C_1D_LOOS",
    "LDA_C_RC04",
    "LDA_C_VWN_1",
    "LDA_C_VWN_2",
    "LDA_C_VWN_3",
    "LDA_C_VWN_4",
    "GGA_X_GAM",
    "GGA_C_GAM",
    "GGA_X_HCTH_A",
    "GGA_X_EV93",
    "HYB_MGGA_X_DLDF",
    "MGGA_C_DLDF",
    "GGA_X_BCGP",
    "GGA_C_ACGGA",
    "GGA_X_LAMBDA_OC2_N",
    "GGA_X_B86_R",
    "MGGA_XC_ZLP",
    "LDA_XC_ZLP",
    "GGA_X_LAMBDA_CH_N",
    "GGA_X_LAMBDA_LO_N",
    "GGA_X_HJS_B88_V2",
    "GGA_C_Q2D",
    "GGA_X_Q2D",
    "GGA_X_PBE_MOL",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_AK13",
    "__unknown__",
    "GGA_X_LV_RPW86",
    "GGA_X_PBE_TCA",
    "GGA_X_PBEINT",
    "GGA_C_ZPBEINT",
    "GGA_C_PBEINT",
    "GGA_C_ZPBESOL",
    "MGGA_XC_OTPSS_D",
    "GGA_XC_OPBE_D",
    "GGA_XC_OPWLYP_D",
    "GGA_XC_OBLYP_D",
    "GGA_X_VMT84_GE",
    "GGA_X_VMT84_PBE",
    "GGA_X_VMT_GE",
    "GGA_X_VMT_PBE",
    "MGGA_C_CS",
    "MGGA_C_MN12_SX",
    "MGGA_C_MN12_L",
    "MGGA_C_M11_L",
    "MGGA_C_M11",
    "MGGA_C_M08_SO",
    "MGGA_C_M08_HX",
    "GGA_C_N12_SX",
    "GGA_C_N12",
    "HYB_GGA_X_N12_SX",
    "GGA_X_N12",
    "GGA_C_REGTPSS",
    "GGA_C_OP_XALPHA",
    "GGA_C_OP_G96",
    "GGA_C_OP_PBE",
    "GGA_C_OP_B88",
    "GGA_C_FT97",
    "GGA_C_SPBE",
    "GGA_X_SSB_SW",
    "GGA_X_SSB",
    "GGA_X_SSB_D",
    "GGA_XC_HCTH_407P",
    "GGA_XC_HCTH_P76",
    "GGA_XC_HCTH_P14",
    "GGA_XC_B97_GGA1",
    "GGA_C_HCTH_A",
    "GGA_X_BPCCAC",
    "GGA_C_REVTCA",
    "GGA_C_TCA",
    "GGA_X_PBE",
    "GGA_X_PBE_R",
    "GGA_X_B86",
    "__unknown__",
    "GGA_X_B86_MGC",
    "GGA_X_B88",
    "GGA_X_G96",
    "GGA_X_PW86",
    "GGA_X_PW91",
    "GGA_X_OPTX",
    "GGA_X_DK87_R1",
    "GGA_X_DK87_R2",
    "GGA_X_LG93",
    "GGA_X_FT97_A",
    "GGA_X_FT97_B",
    "GGA_X_PBE_SOL",
    "GGA_X_RPBE",
    "GGA_X_WC",
    "GGA_X_MPW91",
    "GGA_X_AM05",
    "GGA_X_PBEA",
    "GGA_X_MPBE",
    "GGA_X_XPBE",
    "GGA_X_2D_B86_MGC",
    "GGA_X_BAYESIAN",
    "GGA_X_PBE_JSJR",
    "GGA_X_2D_B88",
    "GGA_X_2D_B86",
    "GGA_X_2D_PBE",
    "GGA_C_PBE",
    "GGA_C_LYP",
    "GGA_C_P86",
    "GGA_C_PBE_SOL",
    "GGA_C_PW91",
    "GGA_C_AM05",
    "GGA_C_XPBE",
    "GGA_C_LM",
    "GGA_C_PBE_JRGX",
    "GGA_X_OPTB88_VDW",
    "GGA_X_PBEK1_VDW",
    "GGA_X_OPTPBE_VDW",
    "GGA_X_RGE2",
    "GGA_C_RGE2",
    "GGA_X_RPW86",
    "GGA_X_KT1",
    "GGA_XC_KT2",
    "GGA_C_WL",
    "GGA_C_WI",
    "GGA_X_MB88",
    "GGA_X_SOGGA",
    "GGA_X_SOGGA11",
    "GGA_C_SOGGA11",
    "GGA_C_WI0",
    "GGA_XC_TH1",
    "GGA_XC_TH2",
    "GGA_XC_TH3",
    "GGA_XC_TH4",
    "GGA_X_C09X",
    "GGA_C_SOGGA11_X",
    "GGA_X_LB",
    "GGA_XC_HCTH_93",
    "GGA_XC_HCTH_120",
    "GGA_XC_HCTH_147",
    "GGA_XC_HCTH_407",
    "GGA_XC_EDF1",
    "GGA_XC_XLYP",
    "GGA_XC_KT1",
    "GGA_X_LSPBE",
    "GGA_X_LSRPBE",
    "GGA_XC_B97_D",
    "GGA_X_OPTB86B_VDW",
    "MGGA_C_REVM11",
    "GGA_XC_PBE1W",
    "GGA_XC_MPWLYP1W",
    "GGA_XC_PBELYP1W",
    "GGA_C_ACGGAP",
    "__unknown__",
    "__unknown__",
    "GGA_X_B88_6311G",
    "GGA_X_NCAP",
    "GGA_XC_NCAP",
    "GGA_X_LBM",
    "GGA_X_OL2",
    "GGA_X_APBE",
    "__unknown__",
    "GGA_C_APBE",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_HTBS",
    "GGA_X_AIRY",
    "GGA_X_LAG",
    "GGA_XC_MOHLYP",
    "GGA_XC_MOHLYP2",
    "GGA_XC_TH_FL",
    "GGA_XC_TH_FC",
    "GGA_XC_TH_FCFO",
    "GGA_XC_TH_FCO",
    "GGA_C_OPTC",
    "MGGA_X_LTA",
    "MGGA_X_TPSS",
    "MGGA_X_M06_L",
    "MGGA_X_GVT4",
    "MGGA_X_TAU_HCTH",
    "MGGA_X_BR89",
    "MGGA_X_BJ06",
    "MGGA_X_TB09",
    "MGGA_X_RPP09",
    "MGGA_X_2D_PRHG07",
    "MGGA_X_2D_PRHG07_PRP10",
    "MGGA_X_REVTPSS",
    "MGGA_X_PKZB",
    "MGGA_X_BR89_1",
    "GGA_X_ECMV92",
    "GGA_C_PBE_VWN",
    "GGA_C_P86_FT",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "MGGA_X_MS0",
    "MGGA_X_MS1",
    "MGGA_X_MS2",
    "HYB_MGGA_X_MS2H",
    "MGGA_X_TH",
    "MGGA_X_M11_L",
    "MGGA_X_MN12_L",
    "MGGA_X_MS2_REV",
    "MGGA_XC_CC06",
    "MGGA_X_MK00",
    "MGGA_C_TPSS",
    "MGGA_C_VSXC",
    "MGGA_C_M06_L",
    "MGGA_C_M06_HF",
    "MGGA_C_M06",
    "MGGA_C_M06_2X",
    "MGGA_C_M05",
    "MGGA_C_M05_2X",
    "MGGA_C_PKZB",
    "MGGA_C_BC95",
    "MGGA_C_REVTPSS",
    "MGGA_XC_TPSSLYP1W",
    "MGGA_X_MK00B",
    "MGGA_X_BLOC",
    "MGGA_X_MODTPSS",
    "GGA_C_PBELOC",
    "MGGA_C_TPSSLOC",
    "HYB_MGGA_X_MN12_SX",
    "MGGA_X_MBEEF",
    "MGGA_X_MBEEFVDW",
    "MGGA_C_TM",
    "GGA_C_P86VWN",
    "GGA_C_P86VWN_FT",
    "MGGA_XC_B97M_V",
    "GGA_XC_VV10",
    "MGGA_X_JK",
    "MGGA_X_MVS",
    "GGA_C_PBEFE",
    "LDA_XC_KSDT",
    "MGGA_X_MN15_L",
    "MGGA_C_MN15_L",
    "GGA_C_OP_PW91",
    "MGGA_X_SCAN",
    "HYB_MGGA_X_SCAN0",
    "GGA_X_PBEFE",
    "HYB_GGA_XC_B97_1P",
    "MGGA_C_SCAN",
    "HYB_MGGA_X_MN15",
    "MGGA_C_MN15",
    "GGA_X_CAP",
    "GGA_X_EB88",
    "GGA_C_PBE_MOL",
    "HYB_GGA_XC_PBE_MOL0",
    "HYB_GGA_XC_PBE_SOL0",
    "HYB_GGA_XC_PBEB0",
    "HYB_GGA_XC_PBE_MOLB0",
    "__unknown__",
    "__unknown__",
    "HYB_MGGA_X_BMK",
    "GGA_C_BMK",
    "GGA_C_TAU_HCTH",
    "HYB_MGGA_X_TAU_HCTH",
    "GGA_C_HYB_TAU_HCTH",
    "MGGA_X_B00",
    "GGA_X_BEEFVDW",
    "GGA_XC_BEEFVDW",
    "LDA_C_CHACHIYO",
    "MGGA_XC_HLE17",
    "LDA_C_LP96",
    "HYB_GGA_XC_PBE50",
    "GGA_X_PBETRANS",
    "MGGA_C_SCAN_RVV10",
    "MGGA_X_REVM06_L",
    "MGGA_C_REVM06_L",
    "HYB_MGGA_X_M08_HX",
    "HYB_MGGA_X_M08_SO",
    "HYB_MGGA_X_M11",
    "GGA_X_CHACHIYO",
    "MGGA_X_RTPSS",
    "MGGA_X_MS2B",
    "MGGA_X_MS2BS",
    "MGGA_X_MVSB",
    "MGGA_X_MVSBS",
    "HYB_MGGA_X_REVM11",
    "HYB_MGGA_X_REVM06",
    "MGGA_C_REVM06",
    "LDA_C_CHACHIYO_MOD",
    "LDA_C_KARASIEV_MOD",
    "GGA_C_CHACHIYO",
    "HYB_MGGA_X_M06_SX",
    "MGGA_C_M06_SX",
    "GGA_X_REVSSB_D",
    "GGA_C_CCDF",
    "HYB_GGA_XC_HFLYP",
    "HYB_GGA_XC_B3P86_NWCHEM",
    "GGA_X_PW91_MOD",
    "LDA_C_W20",
    "LDA_XC_CORRKSDT",
    "MGGA_X_FT98",
    "GGA_X_PBE_MOD",
    "GGA_X_PBE_GAUSSIAN",
    "GGA_C_PBE_GAUSSIAN",
    "MGGA_C_TPSS_GAUSSIAN",
    "GGA_X_NCAPR",
    "HYB_GGA_XC_RELPBE0",
    "MGGA_X_EEL",
    "GGA_XC_B97_3C",
    "LDA_C_EPC17",
    "LDA_C_EPC17_2",
    "LDA_C_EPC18_1",
    "LDA_C_EPC18_2",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_BKL1",
    "GGA_X_BKL2",
    "HYB_MGGA_X_CF22D",
    "MGGA_C_CF22D",
    "MGGA_X_LAK",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "HYB_GGA_XC_OPB3LYP",
    "MGGA_C_CC",
    "MGGA_C_CCALDA",
    "HYB_MGGA_XC_BR3P86",
    "HYB_GGA_XC_CASE21",
    "MGGA_C_RREGTM",
    "HYB_GGA_XC_PBE_2X",
    "HYB_GGA_XC_PBE38",
    "HYB_GGA_XC_B3LYP3",
    "HYB_GGA_XC_CAM_O3LYP",
    "HYB_MGGA_XC_TPSS0",
    "MGGA_C_B94",
    "HYB_MGGA_XC_B94_HYB",
    "HYB_GGA_XC_WB97X_D3",
    "HYB_GGA_XC_LC_BLYP",
    "HYB_GGA_XC_B3PW91",
    "HYB_GGA_XC_B3LYP",
    "HYB_GGA_XC_B3P86",
    "HYB_GGA_XC_O3LYP",
    "HYB_GGA_XC_MPW1K",
    "HYB_GGA_XC_PBEH",
    "HYB_GGA_XC_B97",
    "HYB_GGA_XC_B97_1",
    "HYB_GGA_XC_APF",
    "HYB_GGA_XC_B97_2",
    "HYB_GGA_XC_X3LYP",
    "HYB_GGA_XC_B1WC",
    "HYB_GGA_XC_B97_K",
    "HYB_GGA_XC_B97_3",
    "HYB_GGA_XC_MPW3PW",
    "HYB_GGA_XC_B1LYP",
    "HYB_GGA_XC_B1PW91",
    "HYB_GGA_XC_MPW1PW",
    "HYB_GGA_XC_MPW3LYP",
    "HYB_GGA_XC_SB98_1A",
    "HYB_GGA_XC_SB98_1B",
    "HYB_GGA_XC_SB98_1C",
    "HYB_GGA_XC_SB98_2A",
    "HYB_GGA_XC_SB98_2B",
    "HYB_GGA_XC_SB98_2C",
    "HYB_GGA_X_SOGGA11_X",
    "HYB_GGA_XC_HSE03",
    "HYB_GGA_XC_HSE06",
    "HYB_GGA_XC_HJS_PBE",
    "HYB_GGA_XC_HJS_PBE_SOL",
    "HYB_GGA_XC_HJS_B88",
    "HYB_GGA_XC_HJS_B97X",
    "HYB_GGA_XC_CAM_B3LYP",
    "HYB_GGA_XC_TUNED_CAM_B3LYP",
    "HYB_GGA_XC_BHANDH",
    "HYB_GGA_XC_BHANDHLYP",
    "HYB_GGA_XC_MB3LYP_RC04",
    "HYB_MGGA_X_M05",
    "HYB_MGGA_X_M05_2X",
    "HYB_MGGA_XC_B88B95",
    "HYB_MGGA_XC_B86B95",
    "HYB_MGGA_XC_PW86B95",
    "HYB_MGGA_XC_BB1K",
    "HYB_MGGA_X_M06_HF",
    "HYB_MGGA_XC_MPW1B95",
    "HYB_MGGA_XC_MPWB1K",
    "HYB_MGGA_XC_X1B95",
    "HYB_MGGA_XC_XB1K",
    "HYB_MGGA_X_M06",
    "HYB_MGGA_X_M06_2X",
    "HYB_MGGA_XC_PW6B95",
    "HYB_MGGA_XC_PWB6K",
    "HYB_GGA_XC_MPWLYP1M",
    "HYB_GGA_XC_REVB3LYP",
    "HYB_GGA_XC_CAMY_BLYP",
    "HYB_GGA_XC_PBE0_13",
    "HYB_MGGA_XC_TPSSH",
    "HYB_MGGA_XC_REVTPSSH",
    "HYB_GGA_XC_B3LYPS",
    "HYB_GGA_XC_QTP17",
    "HYB_GGA_XC_B3LYP_MCM1",
    "HYB_GGA_XC_B3LYP_MCM2",
    "HYB_GGA_XC_WB97",
    "HYB_GGA_XC_WB97X",
    "HYB_GGA_XC_LRC_WPBEH",
    "HYB_GGA_XC_WB97X_V",
    "HYB_GGA_XC_LCY_PBE",
    "HYB_GGA_XC_LCY_BLYP",
    "HYB_GGA_XC_LC_VV10",
    "HYB_GGA_XC_CAMY_B3LYP",
    "HYB_GGA_XC_WB97X_D",
    "HYB_GGA_XC_HPBEINT",
    "HYB_GGA_XC_LRC_WPBE",
    "HYB_MGGA_X_MVSH",
    "HYB_GGA_XC_B3LYP5",
    "HYB_GGA_XC_EDF2",
    "HYB_GGA_XC_CAP0",
    "HYB_GGA_XC_LC_WPBE",
    "HYB_GGA_XC_HSE12",
    "HYB_GGA_XC_HSE12S",
    "HYB_GGA_XC_HSE_SOL",
    "HYB_GGA_XC_CAM_QTP_01",
    "HYB_GGA_XC_MPW1LYP",
    "HYB_GGA_XC_MPW1PBE",
    "HYB_GGA_XC_KMLYP",
    "HYB_GGA_XC_LC_WPBE_WHS",
    "HYB_GGA_XC_LC_WPBEH_WHS",
    "HYB_GGA_XC_LC_WPBE08_WHS",
    "HYB_GGA_XC_LC_WPBESOL_WHS",
    "HYB_GGA_XC_CAM_QTP_00",
    "HYB_GGA_XC_CAM_QTP_02",
    "HYB_GGA_XC_LC_QTP",
    "MGGA_X_RSCAN",
    "MGGA_C_RSCAN",
    "GGA_X_S12G",
    "HYB_GGA_X_S12H",
    "MGGA_X_R2SCAN",
    "MGGA_C_R2SCAN",
    "HYB_GGA_XC_BLYP35",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_WPBEH",
    "GGA_X_HJS_PBE",
    "GGA_X_HJS_PBE_SOL",
    "GGA_X_HJS_B88",
    "GGA_X_HJS_B97X",
    "GGA_X_ITYH",
    "GGA_X_SFAT",
    "HYB_MGGA_XC_WB97M_V",
    "LDA_X_REL",
    "GGA_X_SG4",
    "GGA_C_SG4",
    "GGA_X_GG99",
    "LDA_XC_1D_EHWLRG_1",
    "LDA_XC_1D_EHWLRG_2",
    "LDA_XC_1D_EHWLRG_3",
    "GGA_X_PBEPOW",
    "MGGA_X_TM",
    "MGGA_X_VT84",
    "MGGA_X_SA_TPSS",
    "__unknown__",
    "GGA_X_KGG99",
    "GGA_XC_HLE16",
    "LDA_X_ERF",
    "LDA_XC_LP_A",
    "LDA_XC_LP_B",
    "LDA_X_RAE",
    "__unknown__",
    "LDA_C_MCWEENY",
    "LDA_C_BR78",
    "GGA_C_SCAN_E0",
    "LDA_C_PK09",
    "GGA_C_GAPC",
    "GGA_C_GAPLOC",
    "GGA_C_ZVPBEINT",
    "GGA_C_ZVPBESOL",
    "GGA_C_TM_LYP",
    "GGA_C_TM_PBE",
    "GGA_C_W94",
    "MGGA_C_KCIS",
    "HYB_MGGA_XC_B0KCIS",
    "MGGA_XC_LP90",
    "GGA_C_CS1",
    "HYB_MGGA_XC_MPW1KCIS",
    "HYB_MGGA_XC_MPWKCIS1K",
    "HYB_MGGA_XC_PBE1KCIS",
    "HYB_MGGA_XC_TPSS1KCIS",
    "GGA_X_B88M",
    "MGGA_C_B88",
    "HYB_GGA_XC_B5050LYP",
    "LDA_C_OW_LYP",
    "LDA_C_OW",
    "MGGA_X_GX",
    "MGGA_X_PBE_GX",
    "LDA_XC_GDSMFB",
    "LDA_C_GK72",
    "LDA_C_KARASIEV",
    "__unknown__",
    "MGGA_X_REVSCAN",
    "MGGA_C_REVSCAN",
    "HYB_MGGA_X_REVSCAN0",
    "MGGA_C_SCAN_VV10",
    "MGGA_C_REVSCAN_VV10",
    "MGGA_X_BR89_EXPLICIT",
    "GGA_XC_KT3",
    "__unknown__",
    "HYB_GGA_XC_LB07",
    "LDA_C_PMGB06",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "HYB_MGGA_XC_B98",
    "LDA_XC_TIH",
    "LDA_X_1D_EXPONENTIAL",
    "GGA_X_SFAT_PBE",
    "MGGA_X_BR89_EXPLICIT_1",
    "MGGA_X_REGTPSS",
    "GGA_X_FD_LB94",
    "GGA_X_FD_REVLB94",
    "GGA_C_ZVPBELOC",
    "HYB_GGA_XC_APBE0",
    "HYB_GGA_XC_HAPBE",
    "MGGA_X_2D_JS17",
    "HYB_GGA_XC_RCAM_B3LYP",
    "HYB_GGA_XC_WC04",
    "HYB_GGA_XC_WP04",
    "__unknown__",
    "HYB_GGA_XC_CAMH_B3LYP",
    "HYB_GGA_XC_WHPBE0",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_ITYH_OPTX",
    "GGA_X_ITYH_PBE",
    "GGA_C_LYPR",
    "HYB_GGA_XC_LC_BLYP_EA",
    "MGGA_X_REGTM",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "HYB_GGA_XC_LC_BOP",
    "HYB_GGA_XC_LC_PBEOP",
    "MGGA_C_KCISK",
    "HYB_GGA_XC_LC_BLYPR",
    "HYB_GGA_XC_MCAM_B3LYP",
    "LDA_X_YUKAWA",
    "MGGA_C_R2SCAN01",
    "MGGA_C_RMGGAC",
    "MGGA_X_MCML",
    "MGGA_X_R2SCAN01",
    "HYB_GGA_X_CAM_S12G",
    "HYB_GGA_X_CAM_S12H",
    "MGGA_X_RPPSCAN",
    "MGGA_C_RPPSCAN",
    "MGGA_X_R4SCAN",
    "MGGA_X_VCML",
    "MGGA_XC_VCML_RVV10",
    "__unknown__",
    "LDA_C_PW_ERF",
    "GGA_X_PBE_ERF_GWS",
    "HYB_GGA_X_PBE_ERF_GWS",
    "GGA_C_PBE_ERF_GWS",
    "HYB_MGGA_XC_GAS22",
    "HYB_MGGA_XC_R2SCANH",
    "HYB_MGGA_XC_R2SCAN0",
    "HYB_MGGA_XC_R2SCAN50",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "HYB_GGA_XC_CAM_PBEH",
    "HYB_GGA_XC_CAMY_PBEH",
    "LDA_C_UPW92",
    "LDA_C_RPW92",
    "MGGA_X_TLDA",
    "MGGA_X_EDMGGA",
    "MGGA_X_GDME_NV",
    "MGGA_X_RLDA",
    "MGGA_X_GDME_0",
    "MGGA_X_GDME_KOS",
    "MGGA_X_GDME_VT",
    "LDA_X_SLOC",
    "MGGA_X_REVTM",
    "MGGA_C_REVTM",
    "HYB_MGGA_XC_EDMGGAH",
    "MGGA_X_MBRXC_BG",
    "MGGA_X_MBRXH_BG",
    "MGGA_X_HLTA",
    "MGGA_C_HLTAPW",
    "MGGA_X_SCANL",
    "MGGA_X_REVSCANL",
    "MGGA_C_SCANL",
    "MGGA_C_SCANL_RVV10",
    "MGGA_C_SCANL_VV10",
    "HYB_MGGA_X_JS18",
    "HYB_MGGA_X_PJS18",
    "MGGA_X_TASK",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "MGGA_X_MGGAC",
    "GGA_C_MGGAC",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "MGGA_X_MBR",
    "__unknown__",
    "MGGA_X_R2SCANL",
    "MGGA_C_R2SCANL",
    "HYB_MGGA_XC_LC_TMLYP",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "MGGA_X_MTASK",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "__unknown__",
    "GGA_X_Q1D",
    "MGGA_X_KTBM_0",
    "MGGA_X_KTBM_1",
    "MGGA_X_KTBM_2",
    "MGGA_X_KTBM_3",
    "MGGA_X_KTBM_4",
    "MGGA_X_KTBM_5",
    "MGGA_X_KTBM_6",
    "MGGA_X_KTBM_7",
    "MGGA_X_KTBM_8",
    "MGGA_X_KTBM_9",
    "MGGA_X_KTBM_10",
    "MGGA_X_KTBM_11",
    "MGGA_X_KTBM_12",
    "MGGA_X_KTBM_13",
    "MGGA_X_KTBM_14",
    "MGGA_X_KTBM_15",
    "MGGA_X_KTBM_16",
    "MGGA_X_KTBM_17",
    "MGGA_X_KTBM_18",
    "MGGA_X_KTBM_19",
    "MGGA_X_KTBM_20",
    "MGGA_X_KTBM_21",
    "MGGA_X_KTBM_22",
    "MGGA_X_KTBM_23",
    "MGGA_X_KTBM_24",
    "MGGA_X_KTBM_GAP",
    "MGGA_X_MSPBEL",
    "MGGA_X_RMSPBEL",
    "MGGA_X_MSRPBEL",
    "MGGA_X_RMSRPBEL",
    "MGGA_X_MSB86BL",
    "MGGA_X_RMSB86BL"
};

#ifdef USE_LIBXC // compile with -DENABLE_LIBXC=1

std::string XC_Functional_Libxc::get_xcname_from_xcid(const int id) {
    const std::string xcname = mymap_xcid_xcname[id];
    if (xcname == "__unknown__") {
        ModuleBase::WARNING_QUIT(
            "ModuleHamiltGeneral::XC_Functional_Libxc::get_xcname_from_xcid",
            "Unknown xc functional id: " + std::to_string(id));
    }
    return xcname;
}

int XC_Functional_Libxc::get_xcid_from_xcname(const std::string& name) {
    auto it = mymap_xcname_xcid.find(name);
    if (it == mymap_xcname_xcid.end()) {
        ModuleBase::WARNING_QUIT(
            "ModuleHamiltGeneral::XC_Functional_Libxc::get_xcid_from_xcname",
            "Unknown xc functional name: " + name);
    }
    return it->second;
}

#endif // USE_LIBXC
/**
import os
import re
import requests
from bs4 import BeautifulSoup

def write_cxx_stdmap(mydict, inverse=False):
    '''
    output to screen as C++ std::map<std::string, int>
    or its inverse std::vector<std::string>
    '''
    if inverse:
        maxid = max(mydict.values())
        # sort the key-value pairs by value (id)
        mydict = dict(sorted(mydict.items(), key=lambda item: item[1]))
        mydict = {v: k for k, v in mydict.items()}
        # if the id is not in the list, it will be "__unknown__"
        mydict = {v: mydict.get(v, '__unknown__') for v in range(maxid + 1)}
    
    datatyp = 'std::vector<std::string>' if inverse else \
        'std::map<std::string, int>'
    var = 'mymap_xcid_xcname' if inverse else \
        'mymap_xcname_xcid'
    print(f'const {datatyp} {var} = ', end='{\n')
    l = ''
    for k, v in mydict.items():
        l += ' ' * 4 # indentation
        if not inverse:
            l += '{'
        l += f'"{k}", {v}' if not inverse else f'"{v}"'
        if not inverse:
            l += '}'
        l += ',\n'
    l = l[:-2]  # remove last comma and newline
    print(l)
    print('};')

def extract(page):
    # Load the HTML file
    # if the `page` is a file, then use it directly
    if os.path.isfile(page):
        with open(page, encoding='utf-8') as f:
            soup = BeautifulSoup(f, 'html.parser')
    else:
        # If `page` is a URL or other string, you might need to fetch it
        response = requests.get(page)
        if response.status_code != 200:
            raise ValueError(f"Failed to fetch page: {page}")
        soup = BeautifulSoup(response.content, 'html.parser')

    # Regular expression for xc name
    xc_re = re.compile(r'^(LDA|GGA|MGGA|HYB_GGA|HYB_MGGA)_(X|C|XC)_.*')

    mapping = {}

    # Find all <li> with <strong> tags and (id=...) in text
    for li in soup.find_all('li'):
        strong = li.find('strong')
        if strong and strong.string:
            name = strong.string.strip()
            match = xc_re.match(name)
            if match:
            # Find id=xxx in the text
                m = re.search(r'\(id=(\d+)\)', li.text)
                if m:
                    mapping[name] = int(m.group(1))
    return mapping

if __name__ == '__main__':
    # Write the mapping to a C++ std::map
    mapping = extract('https://libxc.gitlab.io/functionals/')
    write_cxx_stdmap(mapping, inverse=True) 
 */