FORTRAN       = ifort

CPLUSPLUS      = icpc

CPLUSPLUS_MPI = mpiicpc

LAPACK_DIR    = $MKLROOT
FFTW_DIR = /home/fortneu49/soft/fftw-3.3.8

BOOST_DIR = /home/fortneu49/soft/boost_1_74_0

ELPA_DIR = /home/fortneu49/soft/elpa-2016.05.004

CEREAL_DIR = /home/fortneu49/soft/cereal-master

LIBTORCH_DIR = /home/fortneu49/soft/libtorch
LIBNPY_DIR = /home/fortneu49/soft/libnpy

OBJ_DIR = obj
NP      = 14
