name: CUDA Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on CUDA Build
    runs-on: nvidia
    container:
      image: ghcr.io/deepmodeling/abacus-cuda
      options: --gpus all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: |
          nvidia-smi
          cmake -B build -DUSE_CUDA=ON -DBUILD_TESTING=ON
          cmake --build build -j4
          cmake --install build
      # TODO: add tests
