name: Build Image

on:
  push:
    branches:
      - develop

jobs:
  build_container_and_push:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'deepmodeling'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Aliyun Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DP_HARBOR_REGISTRY }}
          username: ${{ secrets.DP_HARBOR_USERNAME }}
          password: ${{ secrets.DP_HARBOR_PASSWORD }}

      - name: Build and Push Container
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{ github.repository_owner }}/abacus:latest
            ${{ secrets.DP_HARBOR_REGISTRY }}/dplc/abacus:latest
          file: Dockerfile
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/abacus:latest
          cache-to: type=inline
          push: true
