on: [push]

jobs:
  main:
    env:
      CONTAINER: ghcr.io/deepmodeling/adk:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.PAT }} | docker login ghcr.io -u Unboundwill --password-stdin
      - run: docker pull ${{ env.CONTAINER }}
      - run: docker build . -t ${{ env.CONTAINER }} --cache-from=${{ env.CONTAINER }}
      - run: docker run -v $GITHUB_WORKSPACE:/workspace -w /workspace ${{ env.CONTAINER }} bash entrypoint.sh
      - run: docker push ${{ env.CONTAINER }}
