name: Integration Test and Unit Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: X64
    if: github.repository_owner == 'deepmodeling'
    container:
      image: ghcr.io/deepmodeling/abacus-gnu
      volumes:
        - /tmp/ccache:/github/home/.ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON -DENABLE_DEEPKS=ON -DENABLE_LIBXC=ON -DENABLE_LIBRI=ON -DENABLE_PAW=ON -DENABLE_GOOGLEBENCH=ON -DENABLE_RAPIDJSON=ON  -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          cmake --build build -j8
          cmake --install build
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          cmake --build build --target test ARGS="-V --timeout 1700"
