name: Test

on:
  pull_request:
    branches:
      - develop

env:
  CONTAINER: ghcr.io/deepmodeling/abacus-development-kit:gnu

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: abacus-development-kit:gnu
          cache-from: type=registry,ref=${{ env.CONTAINER }}
      - name: Build and Test
        run: docker run -v $GITHUB_WORKSPACE:/workspace -w /workspace abacus-development-kit:gnu bash entrypoint.sh
